// Code generated by 'yaegi extract github.com/samcharles93/archie-core/internal/domain/workflow'. DO NOT EDIT.

package wfextract

import (
	"context"
	"github.com/samcharles93/archie-core/internal/domain/workflow"
	"reflect"
)

func init() {
	Symbols["github.com/samcharles93/archie-core/internal/domain/workflow/workflow"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bootstrap":                           reflect.ValueOf(workflow.Bootstrap),
		"Definitions":                         reflect.ValueOf(workflow.Definitions),
		"DefinitionsWithOrigins":              reflect.ValueOf(workflow.DefinitionsWithOrigins),
		"Feasibility":                         reflect.ValueOf(workflow.Feasibility),
		"GateFromRepo":                        reflect.ValueOf(workflow.GateFromRepo),
		"Implement":                           reflect.ValueOf(workflow.Implement),
		"LoadKindWorkflowsYAML":               reflect.ValueOf(workflow.LoadKindWorkflowsYAML),
		"LoadLabelWorkflowsYAML":              reflect.ValueOf(workflow.LoadLabelWorkflowsYAML),
		"LoadPlaybookDirs":                    reflect.ValueOf(workflow.LoadPlaybookDirs),
		"MergeKindWorkflows":                  reflect.ValueOf(workflow.MergeKindWorkflows),
		"MergeLabelWorkflows":                 reflect.ValueOf(workflow.MergeLabelWorkflows),
		"NewCompletedReviewReport":            reflect.ValueOf(workflow.NewCompletedReviewReport),
		"NewNotRunReviewReport":               reflect.ValueOf(workflow.NewNotRunReviewReport),
		"NewSkippedReviewReport":              reflect.ValueOf(workflow.NewSkippedReviewReport),
		"OpenPR":                              reflect.ValueOf(workflow.OpenPR),
		"ReviewBlocking":                      reflect.ValueOf(workflow.ReviewBlocking),
		"ReviewCategoryDeadCode":              reflect.ValueOf(workflow.ReviewCategoryDeadCode),
		"ReviewCategoryGoroutineLeak":         reflect.ValueOf(workflow.ReviewCategoryGoroutineLeak),
		"ReviewCategoryHardcodedValue":        reflect.ValueOf(workflow.ReviewCategoryHardcodedValue),
		"ReviewCategoryInterfaceSatisfaction": reflect.ValueOf(workflow.ReviewCategoryInterfaceSatisfaction),
		"ReviewCategoryNilRisk":               reflect.ValueOf(workflow.ReviewCategoryNilRisk),
		"ReviewCategoryOther":                 reflect.ValueOf(workflow.ReviewCategoryOther),
		"ReviewCategoryRace":                  reflect.ValueOf(workflow.ReviewCategoryRace),
		"ReviewCategoryUncheckedError":        reflect.ValueOf(workflow.ReviewCategoryUncheckedError),
		"ReviewDispositionFixed":              reflect.ValueOf(workflow.ReviewDispositionFixed),
		"ReviewDispositionNoChangeNeeded":     reflect.ValueOf(workflow.ReviewDispositionNoChangeNeeded),
		"ReviewDispositionSkipped":            reflect.ValueOf(workflow.ReviewDispositionSkipped),
		"ReviewLevelError":                    reflect.ValueOf(workflow.ReviewLevelError),
		"ReviewLevelWarn":                     reflect.ValueOf(workflow.ReviewLevelWarn),
		"ReviewStatusCompleted":               reflect.ValueOf(workflow.ReviewStatusCompleted),
		"ReviewStatusNotRun":                  reflect.ValueOf(workflow.ReviewStatusNotRun),
		"ReviewStatusSkipped":                 reflect.ValueOf(workflow.ReviewStatusSkipped),
		"ReviewVerdictConfirmed":              reflect.ValueOf(workflow.ReviewVerdictConfirmed),
		"ReviewVerdictPlausible":              reflect.ValueOf(workflow.ReviewVerdictPlausible),
		"Route":                               reflect.ValueOf(workflow.Route),
		"Run":                                 reflect.ValueOf(workflow.Run),
		"SetKindWorkflows":                    reflect.ValueOf(workflow.SetKindWorkflows),
		"SetLabelWorkflows":                   reflect.ValueOf(workflow.SetLabelWorkflows),
		"StageBaselineGate":                   reflect.ValueOf(workflow.StageBaselineGate),
		"StageCommit":                         reflect.ValueOf(workflow.StageCommit),
		"StageCommitPush":                     reflect.ValueOf(workflow.StageCommitPush),
		"StageDiffCap":                        reflect.ValueOf(workflow.StageDiffCap),
		"StageOpenPR":                         reflect.ValueOf(workflow.StageOpenPR),
		"StagePrepareWorktree":                reflect.ValueOf(workflow.StagePrepareWorktree),
		"StageRepoStages":                     reflect.ValueOf(workflow.StageRepoStages),
		"StageReview":                         reflect.ValueOf(workflow.StageReview),
		"StageYaegiGate":                      reflect.ValueOf(workflow.StageYaegiGate),
		"TDD":                                 reflect.ValueOf(workflow.TDD),
		"Triage":                              reflect.ValueOf(workflow.Triage),

		// type definitions
		"AgentStage":        reflect.ValueOf((*workflow.AgentStage)(nil)),
		"Definition":        reflect.ValueOf((*workflow.Definition)(nil)),
		"Forger":            reflect.ValueOf((*workflow.Forger)(nil)),
		"KindWorkflows":     reflect.ValueOf((*workflow.KindWorkflows)(nil)),
		"LabelWorkflows":    reflect.ValueOf((*workflow.LabelWorkflows)(nil)),
		"Outcome":           reflect.ValueOf((*workflow.Outcome)(nil)),
		"Registry":          reflect.ValueOf((*workflow.Registry)(nil)),
		"ReviewCategory":    reflect.ValueOf((*workflow.ReviewCategory)(nil)),
		"ReviewDisposition": reflect.ValueOf((*workflow.ReviewDisposition)(nil)),
		"ReviewFinding":     reflect.ValueOf((*workflow.ReviewFinding)(nil)),
		"ReviewLevel":       reflect.ValueOf((*workflow.ReviewLevel)(nil)),
		"ReviewReport":      reflect.ValueOf((*workflow.ReviewReport)(nil)),
		"ReviewRequest":     reflect.ValueOf((*workflow.ReviewRequest)(nil)),
		"ReviewStatus":      reflect.ValueOf((*workflow.ReviewStatus)(nil)),
		"ReviewVerdict":     reflect.ValueOf((*workflow.ReviewVerdict)(nil)),
		"Reviewer":          reflect.ValueOf((*workflow.Reviewer)(nil)),
		"Stage":             reflect.ValueOf((*workflow.Stage)(nil)),
		"TaskContext":       reflect.ValueOf((*workflow.TaskContext)(nil)),
		"Trees":             reflect.ValueOf((*workflow.Trees)(nil)),
		"Workflow":          reflect.ValueOf((*workflow.Workflow)(nil)),

		// interface wrapper definitions
		"_Forger":   reflect.ValueOf((*_github_com_samcharles93_archie_core_internal_domain_workflow_Forger)(nil)),
		"_Reviewer": reflect.ValueOf((*_github_com_samcharles93_archie_core_internal_domain_workflow_Reviewer)(nil)),
		"_Trees":    reflect.ValueOf((*_github_com_samcharles93_archie_core_internal_domain_workflow_Trees)(nil)),
	}
}

// _github_com_samcharles93_archie_core_internal_domain_workflow_Forger is an interface wrapper for Forger type
type _github_com_samcharles93_archie_core_internal_domain_workflow_Forger struct {
	IValue      interface{}
	WCloseIssue func(ctx context.Context, owner string, repo string, number int, comment string) error
	WCreatePR   func(ctx context.Context, owner string, repo string, title string, head string, base string, body string) (int, error)
	WLinkBranch func(ctx context.Context, owner string, repo string, issueNumber int, branch string) error
}

func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Forger) CloseIssue(ctx context.Context, owner string, repo string, number int, comment string) error {
	if W.WCloseIssue == nil {
		return nil
	}
	return W.WCloseIssue(ctx, owner, repo, number, comment)
}
func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Forger) CreatePR(ctx context.Context, owner string, repo string, title string, head string, base string, body string) (int, error) {
	if W.WCreatePR == nil {
		return 0, nil
	}
	return W.WCreatePR(ctx, owner, repo, title, head, base, body)
}
func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Forger) LinkBranch(ctx context.Context, owner string, repo string, issueNumber int, branch string) error {
	if W.WLinkBranch == nil {
		return nil
	}
	return W.WLinkBranch(ctx, owner, repo, issueNumber, branch)
}

// _github_com_samcharles93_archie_core_internal_domain_workflow_Reviewer is an interface wrapper for Reviewer type
type _github_com_samcharles93_archie_core_internal_domain_workflow_Reviewer struct {
	IValue  interface{}
	WReview func(ctx context.Context, req workflow.ReviewRequest) workflow.ReviewReport
}

func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Reviewer) Review(ctx context.Context, req workflow.ReviewRequest) workflow.ReviewReport {
	if W.WReview == nil {
		return workflow.ReviewReport{}
	}
	return W.WReview(ctx, req)
}

// _github_com_samcharles93_archie_core_internal_domain_workflow_Trees is an interface wrapper for Trees type
type _github_com_samcharles93_archie_core_internal_domain_workflow_Trees struct {
	IValue        interface{}
	WChangedFiles func(ctx context.Context, dir string, base string) ([]string, error)
	WChangedLines func(ctx context.Context, dir string, base string) (int, error)
	WCommitAll    func(ctx context.Context, dir string, message string) (bool, error)
	WDiff         func(ctx context.Context, dir string, base string) (string, error)
	WPrepare      func(ctx context.Context, owner string, repo string, base string, issue int, title string, body string, labels string) (dir string, branch string, err error)
	WPush         func(ctx context.Context, dir string, branch string) error
	WSnapshot     func(ctx context.Context, dir string, destDir string) error
}

func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Trees) ChangedFiles(ctx context.Context, dir string, base string) ([]string, error) {
	if W.WChangedFiles == nil {
		return nil, nil
	}
	return W.WChangedFiles(ctx, dir, base)
}
func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Trees) ChangedLines(ctx context.Context, dir string, base string) (int, error) {
	if W.WChangedLines == nil {
		return 0, nil
	}
	return W.WChangedLines(ctx, dir, base)
}
func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Trees) CommitAll(ctx context.Context, dir string, message string) (bool, error) {
	if W.WCommitAll == nil {
		return false, nil
	}
	return W.WCommitAll(ctx, dir, message)
}
func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Trees) Diff(ctx context.Context, dir string, base string) (string, error) {
	if W.WDiff == nil {
		return "", nil
	}
	return W.WDiff(ctx, dir, base)
}
func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Trees) Prepare(ctx context.Context, owner string, repo string, base string, issue int, title string, body string, labels string) (dir string, branch string, err error) {
	if W.WPrepare == nil {
		return "", "", nil
	}
	return W.WPrepare(ctx, owner, repo, base, issue, title, body, labels)
}
func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Trees) Push(ctx context.Context, dir string, branch string) error {
	if W.WPush == nil {
		return nil
	}
	return W.WPush(ctx, dir, branch)
}
func (W _github_com_samcharles93_archie_core_internal_domain_workflow_Trees) Snapshot(ctx context.Context, dir string, destDir string) error {
	if W.WSnapshot == nil {
		return nil
	}
	return W.WSnapshot(ctx, dir, destDir)
}
