// Package wfextract holds the Yaegi symbol table for internal/domain/workflow,
// generated by `go generate`. Kept separate from internal/domain/workflow
// itself so the generated file can import it without a self-import cycle.
//
// The generated file is used verbatim. A wrapper whose method fields are not
// all populated is refused in yaegiutil.Resolve, so it needs no hand-added
// nil-guards -- an earlier convention that every regeneration silently undid.
package wfextract

import "reflect"

//go:generate go run github.com/traefik/yaegi/cmd/yaegi extract -name wfextract github.com/samcharles93/archie-core/internal/domain/workflow

var Symbols = map[string]map[string]reflect.Value{}
