// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: state/v1/state.proto

package statev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StateStoreService_RegisterTaskGrant_FullMethodName          = "/state.v1.StateStoreService/RegisterTaskGrant"
	StateStoreService_RevokeTaskGrant_FullMethodName            = "/state.v1.StateStoreService/RevokeTaskGrant"
	StateStoreService_EnqueueIssue_FullMethodName               = "/state.v1.StateStoreService/EnqueueIssue"
	StateStoreService_EnqueueChatTask_FullMethodName            = "/state.v1.StateStoreService/EnqueueChatTask"
	StateStoreService_ClaimNext_FullMethodName                  = "/state.v1.StateStoreService/ClaimNext"
	StateStoreService_ClaimByIssue_FullMethodName               = "/state.v1.StateStoreService/ClaimByIssue"
	StateStoreService_Transition_FullMethodName                 = "/state.v1.StateStoreService/Transition"
	StateStoreService_Update_FullMethodName                     = "/state.v1.StateStoreService/Update"
	StateStoreService_Requeue_FullMethodName                    = "/state.v1.StateStoreService/Requeue"
	StateStoreService_RecoverStale_FullMethodName               = "/state.v1.StateStoreService/RecoverStale"
	StateStoreService_ArchiveTask_FullMethodName                = "/state.v1.StateStoreService/ArchiveTask"
	StateStoreService_RetryTask_FullMethodName                  = "/state.v1.StateStoreService/RetryTask"
	StateStoreService_TaskByIssue_FullMethodName                = "/state.v1.StateStoreService/TaskByIssue"
	StateStoreService_TaskByID_FullMethodName                   = "/state.v1.StateStoreService/TaskByID"
	StateStoreService_OpenPRs_FullMethodName                    = "/state.v1.StateStoreService/OpenPRs"
	StateStoreService_ClearTerminalTasks_FullMethodName         = "/state.v1.StateStoreService/ClearTerminalTasks"
	StateStoreService_Tasks_FullMethodName                      = "/state.v1.StateStoreService/Tasks"
	StateStoreService_StatusCounts_FullMethodName               = "/state.v1.StateStoreService/StatusCounts"
	StateStoreService_IncrementRetryCount_FullMethodName        = "/state.v1.StateStoreService/IncrementRetryCount"
	StateStoreService_InsertEvent_FullMethodName                = "/state.v1.StateStoreService/InsertEvent"
	StateStoreService_EventsSince_FullMethodName                = "/state.v1.StateStoreService/EventsSince"
	StateStoreService_TaskEvents_FullMethodName                 = "/state.v1.StateStoreService/TaskEvents"
	StateStoreService_WorkflowStats_FullMethodName              = "/state.v1.StateStoreService/WorkflowStats"
	StateStoreService_StageStats_FullMethodName                 = "/state.v1.StateStoreService/StageStats"
	StateStoreService_TokensByDay_FullMethodName                = "/state.v1.StateStoreService/TokensByDay"
	StateStoreService_PutConfigSnapshot_FullMethodName          = "/state.v1.StateStoreService/PutConfigSnapshot"
	StateStoreService_GetConfigSnapshot_FullMethodName          = "/state.v1.StateStoreService/GetConfigSnapshot"
	StateStoreService_InsertCapture_FullMethodName              = "/state.v1.StateStoreService/InsertCapture"
	StateStoreService_ListCaptures_FullMethodName               = "/state.v1.StateStoreService/ListCaptures"
	StateStoreService_StreamCaptures_FullMethodName             = "/state.v1.StateStoreService/StreamCaptures"
	StateStoreService_InsertMapping_FullMethodName              = "/state.v1.StateStoreService/InsertMapping"
	StateStoreService_GetMapping_FullMethodName                 = "/state.v1.StateStoreService/GetMapping"
	StateStoreService_ListMappings_FullMethodName               = "/state.v1.StateStoreService/ListMappings"
	StateStoreService_UpdateMapping_FullMethodName              = "/state.v1.StateStoreService/UpdateMapping"
	StateStoreService_DeleteMapping_FullMethodName              = "/state.v1.StateStoreService/DeleteMapping"
	StateStoreService_InsertBinding_FullMethodName              = "/state.v1.StateStoreService/InsertBinding"
	StateStoreService_GetBinding_FullMethodName                 = "/state.v1.StateStoreService/GetBinding"
	StateStoreService_ListBindings_FullMethodName               = "/state.v1.StateStoreService/ListBindings"
	StateStoreService_UpdateBinding_FullMethodName              = "/state.v1.StateStoreService/UpdateBinding"
	StateStoreService_DeleteBinding_FullMethodName              = "/state.v1.StateStoreService/DeleteBinding"
	StateStoreService_ApproveBinding_FullMethodName             = "/state.v1.StateStoreService/ApproveBinding"
	StateStoreService_ArmedBindingsForSource_FullMethodName     = "/state.v1.StateStoreService/ArmedBindingsForSource"
	StateStoreService_RecordDispatch_FullMethodName             = "/state.v1.StateStoreService/RecordDispatch"
	StateStoreService_ListUndispatchedCaptures_FullMethodName   = "/state.v1.StateStoreService/ListUndispatchedCaptures"
	StateStoreService_StreamUndispatchedCaptures_FullMethodName = "/state.v1.StateStoreService/StreamUndispatchedCaptures"
	StateStoreService_EnqueueBindingTask_FullMethodName         = "/state.v1.StateStoreService/EnqueueBindingTask"
)

// StateStoreServiceClient is the client API for StateStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StateStore is the single gRPC service fronting archie.db (one store, one
// file). See docs/prds/state-store-contract.md for the ownership split: the
// workflow-domain Store view (Update/Transition/InsertEvent) is consumer-owned
// in internal/domain/workflow, while the rest of this surface stays
// producer-owned in internal/store. Both are served by the same service and
// the same *store.Store implementation; the proto bypasses the Go
// interfacebloat cap (max 8), like gateway.v1.ChatService does.
type StateStoreServiceClient interface {
	// Administrative task credential lifecycle. Worker credentials cannot call these.
	RegisterTaskGrant(ctx context.Context, in *RegisterTaskGrantRequest, opts ...grpc.CallOption) (*RegisterTaskGrantResponse, error)
	RevokeTaskGrant(ctx context.Context, in *RevokeTaskGrantRequest, opts ...grpc.CallOption) (*RevokeTaskGrantResponse, error)
	// Lifecycle
	EnqueueIssue(ctx context.Context, in *EnqueueIssueRequest, opts ...grpc.CallOption) (*EnqueueIssueResponse, error)
	EnqueueChatTask(ctx context.Context, in *EnqueueChatTaskRequest, opts ...grpc.CallOption) (*EnqueueChatTaskResponse, error)
	ClaimNext(ctx context.Context, in *ClaimNextRequest, opts ...grpc.CallOption) (*ClaimNextResponse, error)
	ClaimByIssue(ctx context.Context, in *ClaimByIssueRequest, opts ...grpc.CallOption) (*ClaimByIssueResponse, error)
	Transition(ctx context.Context, in *TransitionRequest, opts ...grpc.CallOption) (*TransitionResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Requeue(ctx context.Context, in *RequeueRequest, opts ...grpc.CallOption) (*RequeueResponse, error)
	RecoverStale(ctx context.Context, in *RecoverStaleRequest, opts ...grpc.CallOption) (*RecoverStaleResponse, error)
	// Archive / Retry
	ArchiveTask(ctx context.Context, in *ArchiveTaskRequest, opts ...grpc.CallOption) (*ArchiveTaskResponse, error)
	RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*RetryTaskResponse, error)
	// Queries
	TaskByIssue(ctx context.Context, in *TaskByIssueRequest, opts ...grpc.CallOption) (*TaskByIssueResponse, error)
	TaskByID(ctx context.Context, in *TaskByIDRequest, opts ...grpc.CallOption) (*TaskByIDResponse, error)
	OpenPRs(ctx context.Context, in *OpenPRsRequest, opts ...grpc.CallOption) (*OpenPRsResponse, error)
	ClearTerminalTasks(ctx context.Context, in *ClearTerminalTasksRequest, opts ...grpc.CallOption) (*ClearTerminalTasksResponse, error)
	Tasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (*TasksResponse, error)
	StatusCounts(ctx context.Context, in *StatusCountsRequest, opts ...grpc.CallOption) (*StatusCountsResponse, error)
	IncrementRetryCount(ctx context.Context, in *IncrementRetryCountRequest, opts ...grpc.CallOption) (*IncrementRetryCountResponse, error)
	// Events
	InsertEvent(ctx context.Context, in *InsertEventRequest, opts ...grpc.CallOption) (*InsertEventResponse, error)
	EventsSince(ctx context.Context, in *EventsSinceRequest, opts ...grpc.CallOption) (*EventsSinceResponse, error)
	TaskEvents(ctx context.Context, in *TaskEventsRequest, opts ...grpc.CallOption) (*TaskEventsResponse, error)
	WorkflowStats(ctx context.Context, in *WorkflowStatsRequest, opts ...grpc.CallOption) (*WorkflowStatsResponse, error)
	StageStats(ctx context.Context, in *StageStatsRequest, opts ...grpc.CallOption) (*StageStatsResponse, error)
	TokensByDay(ctx context.Context, in *TokensByDayRequest, opts ...grpc.CallOption) (*TokensByDayResponse, error)
	// Configuration snapshot: the running configuration as the dashboard
	// renders it, published by the owner of configuration for the process that
	// displays it. PutConfigSnapshot is administrative; GetConfigSnapshot is
	// the UI's read (docs/architecture/migration-decisions.md, "Dashboard
	// configuration page").
	PutConfigSnapshot(ctx context.Context, in *PutConfigSnapshotRequest, opts ...grpc.CallOption) (*PutConfigSnapshotResponse, error)
	GetConfigSnapshot(ctx context.Context, in *GetConfigSnapshotRequest, opts ...grpc.CallOption) (*GetConfigSnapshotResponse, error)
	// Capture
	InsertCapture(ctx context.Context, in *InsertCaptureRequest, opts ...grpc.CallOption) (*InsertCaptureResponse, error)
	// Deprecated: Do not use.
	// ListCaptures is superseded by StreamCaptures (kept, unmodified, so an
	// in-flight rolling deploy's old client/server pairing keeps working --
	// buf breaking forbids removing or reshaping an existing RPC). Every
	// in-repo caller uses StreamCaptures.
	ListCaptures(ctx context.Context, in *ListCapturesRequest, opts ...grpc.CallOption) (*ListCapturesResponse, error)
	// StreamCaptures returns one capture per message: a batch of large capture
	// bodies can exceed gRPC's 4MiB unary message cap
	// (docs/prds/state-store-contract.md).
	StreamCaptures(ctx context.Context, in *StreamCapturesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamCapturesResponse], error)
	// Mapping
	InsertMapping(ctx context.Context, in *InsertMappingRequest, opts ...grpc.CallOption) (*InsertMappingResponse, error)
	GetMapping(ctx context.Context, in *GetMappingRequest, opts ...grpc.CallOption) (*GetMappingResponse, error)
	ListMappings(ctx context.Context, in *ListMappingsRequest, opts ...grpc.CallOption) (*ListMappingsResponse, error)
	UpdateMapping(ctx context.Context, in *UpdateMappingRequest, opts ...grpc.CallOption) (*UpdateMappingResponse, error)
	DeleteMapping(ctx context.Context, in *DeleteMappingRequest, opts ...grpc.CallOption) (*DeleteMappingResponse, error)
	// Binding
	InsertBinding(ctx context.Context, in *InsertBindingRequest, opts ...grpc.CallOption) (*InsertBindingResponse, error)
	GetBinding(ctx context.Context, in *GetBindingRequest, opts ...grpc.CallOption) (*GetBindingResponse, error)
	ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*ListBindingsResponse, error)
	UpdateBinding(ctx context.Context, in *UpdateBindingRequest, opts ...grpc.CallOption) (*UpdateBindingResponse, error)
	DeleteBinding(ctx context.Context, in *DeleteBindingRequest, opts ...grpc.CallOption) (*DeleteBindingResponse, error)
	ApproveBinding(ctx context.Context, in *ApproveBindingRequest, opts ...grpc.CallOption) (*ApproveBindingResponse, error)
	// Dispatch
	ArmedBindingsForSource(ctx context.Context, in *ArmedBindingsForSourceRequest, opts ...grpc.CallOption) (*ArmedBindingsForSourceResponse, error)
	RecordDispatch(ctx context.Context, in *RecordDispatchRequest, opts ...grpc.CallOption) (*RecordDispatchResponse, error)
	// Deprecated: Do not use.
	// ListUndispatchedCaptures is superseded by StreamUndispatchedCaptures; see
	// ListCaptures above.
	ListUndispatchedCaptures(ctx context.Context, in *ListUndispatchedCapturesRequest, opts ...grpc.CallOption) (*ListUndispatchedCapturesResponse, error)
	StreamUndispatchedCaptures(ctx context.Context, in *StreamUndispatchedCapturesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamUndispatchedCapturesResponse], error)
	// BindingTaskCreator
	EnqueueBindingTask(ctx context.Context, in *EnqueueBindingTaskRequest, opts ...grpc.CallOption) (*EnqueueBindingTaskResponse, error)
}

type stateStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateStoreServiceClient(cc grpc.ClientConnInterface) StateStoreServiceClient {
	return &stateStoreServiceClient{cc}
}

func (c *stateStoreServiceClient) RegisterTaskGrant(ctx context.Context, in *RegisterTaskGrantRequest, opts ...grpc.CallOption) (*RegisterTaskGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTaskGrantResponse)
	err := c.cc.Invoke(ctx, StateStoreService_RegisterTaskGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) RevokeTaskGrant(ctx context.Context, in *RevokeTaskGrantRequest, opts ...grpc.CallOption) (*RevokeTaskGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeTaskGrantResponse)
	err := c.cc.Invoke(ctx, StateStoreService_RevokeTaskGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) EnqueueIssue(ctx context.Context, in *EnqueueIssueRequest, opts ...grpc.CallOption) (*EnqueueIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueIssueResponse)
	err := c.cc.Invoke(ctx, StateStoreService_EnqueueIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) EnqueueChatTask(ctx context.Context, in *EnqueueChatTaskRequest, opts ...grpc.CallOption) (*EnqueueChatTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueChatTaskResponse)
	err := c.cc.Invoke(ctx, StateStoreService_EnqueueChatTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) ClaimNext(ctx context.Context, in *ClaimNextRequest, opts ...grpc.CallOption) (*ClaimNextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimNextResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ClaimNext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) ClaimByIssue(ctx context.Context, in *ClaimByIssueRequest, opts ...grpc.CallOption) (*ClaimByIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimByIssueResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ClaimByIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) Transition(ctx context.Context, in *TransitionRequest, opts ...grpc.CallOption) (*TransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionResponse)
	err := c.cc.Invoke(ctx, StateStoreService_Transition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, StateStoreService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) Requeue(ctx context.Context, in *RequeueRequest, opts ...grpc.CallOption) (*RequeueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequeueResponse)
	err := c.cc.Invoke(ctx, StateStoreService_Requeue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) RecoverStale(ctx context.Context, in *RecoverStaleRequest, opts ...grpc.CallOption) (*RecoverStaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverStaleResponse)
	err := c.cc.Invoke(ctx, StateStoreService_RecoverStale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) ArchiveTask(ctx context.Context, in *ArchiveTaskRequest, opts ...grpc.CallOption) (*ArchiveTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveTaskResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ArchiveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*RetryTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryTaskResponse)
	err := c.cc.Invoke(ctx, StateStoreService_RetryTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) TaskByIssue(ctx context.Context, in *TaskByIssueRequest, opts ...grpc.CallOption) (*TaskByIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskByIssueResponse)
	err := c.cc.Invoke(ctx, StateStoreService_TaskByIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) TaskByID(ctx context.Context, in *TaskByIDRequest, opts ...grpc.CallOption) (*TaskByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskByIDResponse)
	err := c.cc.Invoke(ctx, StateStoreService_TaskByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) OpenPRs(ctx context.Context, in *OpenPRsRequest, opts ...grpc.CallOption) (*OpenPRsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenPRsResponse)
	err := c.cc.Invoke(ctx, StateStoreService_OpenPRs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) ClearTerminalTasks(ctx context.Context, in *ClearTerminalTasksRequest, opts ...grpc.CallOption) (*ClearTerminalTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearTerminalTasksResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ClearTerminalTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) Tasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (*TasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksResponse)
	err := c.cc.Invoke(ctx, StateStoreService_Tasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) StatusCounts(ctx context.Context, in *StatusCountsRequest, opts ...grpc.CallOption) (*StatusCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusCountsResponse)
	err := c.cc.Invoke(ctx, StateStoreService_StatusCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) IncrementRetryCount(ctx context.Context, in *IncrementRetryCountRequest, opts ...grpc.CallOption) (*IncrementRetryCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementRetryCountResponse)
	err := c.cc.Invoke(ctx, StateStoreService_IncrementRetryCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) InsertEvent(ctx context.Context, in *InsertEventRequest, opts ...grpc.CallOption) (*InsertEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertEventResponse)
	err := c.cc.Invoke(ctx, StateStoreService_InsertEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) EventsSince(ctx context.Context, in *EventsSinceRequest, opts ...grpc.CallOption) (*EventsSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsSinceResponse)
	err := c.cc.Invoke(ctx, StateStoreService_EventsSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) TaskEvents(ctx context.Context, in *TaskEventsRequest, opts ...grpc.CallOption) (*TaskEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskEventsResponse)
	err := c.cc.Invoke(ctx, StateStoreService_TaskEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) WorkflowStats(ctx context.Context, in *WorkflowStatsRequest, opts ...grpc.CallOption) (*WorkflowStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowStatsResponse)
	err := c.cc.Invoke(ctx, StateStoreService_WorkflowStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) StageStats(ctx context.Context, in *StageStatsRequest, opts ...grpc.CallOption) (*StageStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageStatsResponse)
	err := c.cc.Invoke(ctx, StateStoreService_StageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) TokensByDay(ctx context.Context, in *TokensByDayRequest, opts ...grpc.CallOption) (*TokensByDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokensByDayResponse)
	err := c.cc.Invoke(ctx, StateStoreService_TokensByDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) PutConfigSnapshot(ctx context.Context, in *PutConfigSnapshotRequest, opts ...grpc.CallOption) (*PutConfigSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutConfigSnapshotResponse)
	err := c.cc.Invoke(ctx, StateStoreService_PutConfigSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) GetConfigSnapshot(ctx context.Context, in *GetConfigSnapshotRequest, opts ...grpc.CallOption) (*GetConfigSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigSnapshotResponse)
	err := c.cc.Invoke(ctx, StateStoreService_GetConfigSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) InsertCapture(ctx context.Context, in *InsertCaptureRequest, opts ...grpc.CallOption) (*InsertCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertCaptureResponse)
	err := c.cc.Invoke(ctx, StateStoreService_InsertCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *stateStoreServiceClient) ListCaptures(ctx context.Context, in *ListCapturesRequest, opts ...grpc.CallOption) (*ListCapturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCapturesResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ListCaptures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) StreamCaptures(ctx context.Context, in *StreamCapturesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamCapturesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateStoreService_ServiceDesc.Streams[0], StateStoreService_StreamCaptures_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCapturesRequest, StreamCapturesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateStoreService_StreamCapturesClient = grpc.ServerStreamingClient[StreamCapturesResponse]

func (c *stateStoreServiceClient) InsertMapping(ctx context.Context, in *InsertMappingRequest, opts ...grpc.CallOption) (*InsertMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertMappingResponse)
	err := c.cc.Invoke(ctx, StateStoreService_InsertMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) GetMapping(ctx context.Context, in *GetMappingRequest, opts ...grpc.CallOption) (*GetMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMappingResponse)
	err := c.cc.Invoke(ctx, StateStoreService_GetMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) ListMappings(ctx context.Context, in *ListMappingsRequest, opts ...grpc.CallOption) (*ListMappingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMappingsResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ListMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) UpdateMapping(ctx context.Context, in *UpdateMappingRequest, opts ...grpc.CallOption) (*UpdateMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMappingResponse)
	err := c.cc.Invoke(ctx, StateStoreService_UpdateMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) DeleteMapping(ctx context.Context, in *DeleteMappingRequest, opts ...grpc.CallOption) (*DeleteMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMappingResponse)
	err := c.cc.Invoke(ctx, StateStoreService_DeleteMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) InsertBinding(ctx context.Context, in *InsertBindingRequest, opts ...grpc.CallOption) (*InsertBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertBindingResponse)
	err := c.cc.Invoke(ctx, StateStoreService_InsertBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) GetBinding(ctx context.Context, in *GetBindingRequest, opts ...grpc.CallOption) (*GetBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBindingResponse)
	err := c.cc.Invoke(ctx, StateStoreService_GetBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*ListBindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBindingsResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ListBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) UpdateBinding(ctx context.Context, in *UpdateBindingRequest, opts ...grpc.CallOption) (*UpdateBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBindingResponse)
	err := c.cc.Invoke(ctx, StateStoreService_UpdateBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) DeleteBinding(ctx context.Context, in *DeleteBindingRequest, opts ...grpc.CallOption) (*DeleteBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBindingResponse)
	err := c.cc.Invoke(ctx, StateStoreService_DeleteBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) ApproveBinding(ctx context.Context, in *ApproveBindingRequest, opts ...grpc.CallOption) (*ApproveBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveBindingResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ApproveBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) ArmedBindingsForSource(ctx context.Context, in *ArmedBindingsForSourceRequest, opts ...grpc.CallOption) (*ArmedBindingsForSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArmedBindingsForSourceResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ArmedBindingsForSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) RecordDispatch(ctx context.Context, in *RecordDispatchRequest, opts ...grpc.CallOption) (*RecordDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordDispatchResponse)
	err := c.cc.Invoke(ctx, StateStoreService_RecordDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *stateStoreServiceClient) ListUndispatchedCaptures(ctx context.Context, in *ListUndispatchedCapturesRequest, opts ...grpc.CallOption) (*ListUndispatchedCapturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUndispatchedCapturesResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ListUndispatchedCaptures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) StreamUndispatchedCaptures(ctx context.Context, in *StreamUndispatchedCapturesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamUndispatchedCapturesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StateStoreService_ServiceDesc.Streams[1], StateStoreService_StreamUndispatchedCaptures_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamUndispatchedCapturesRequest, StreamUndispatchedCapturesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateStoreService_StreamUndispatchedCapturesClient = grpc.ServerStreamingClient[StreamUndispatchedCapturesResponse]

func (c *stateStoreServiceClient) EnqueueBindingTask(ctx context.Context, in *EnqueueBindingTaskRequest, opts ...grpc.CallOption) (*EnqueueBindingTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueBindingTaskResponse)
	err := c.cc.Invoke(ctx, StateStoreService_EnqueueBindingTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateStoreServiceServer is the server API for StateStoreService service.
// All implementations must embed UnimplementedStateStoreServiceServer
// for forward compatibility.
//
// StateStore is the single gRPC service fronting archie.db (one store, one
// file). See docs/prds/state-store-contract.md for the ownership split: the
// workflow-domain Store view (Update/Transition/InsertEvent) is consumer-owned
// in internal/domain/workflow, while the rest of this surface stays
// producer-owned in internal/store. Both are served by the same service and
// the same *store.Store implementation; the proto bypasses the Go
// interfacebloat cap (max 8), like gateway.v1.ChatService does.
type StateStoreServiceServer interface {
	// Administrative task credential lifecycle. Worker credentials cannot call these.
	RegisterTaskGrant(context.Context, *RegisterTaskGrantRequest) (*RegisterTaskGrantResponse, error)
	RevokeTaskGrant(context.Context, *RevokeTaskGrantRequest) (*RevokeTaskGrantResponse, error)
	// Lifecycle
	EnqueueIssue(context.Context, *EnqueueIssueRequest) (*EnqueueIssueResponse, error)
	EnqueueChatTask(context.Context, *EnqueueChatTaskRequest) (*EnqueueChatTaskResponse, error)
	ClaimNext(context.Context, *ClaimNextRequest) (*ClaimNextResponse, error)
	ClaimByIssue(context.Context, *ClaimByIssueRequest) (*ClaimByIssueResponse, error)
	Transition(context.Context, *TransitionRequest) (*TransitionResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Requeue(context.Context, *RequeueRequest) (*RequeueResponse, error)
	RecoverStale(context.Context, *RecoverStaleRequest) (*RecoverStaleResponse, error)
	// Archive / Retry
	ArchiveTask(context.Context, *ArchiveTaskRequest) (*ArchiveTaskResponse, error)
	RetryTask(context.Context, *RetryTaskRequest) (*RetryTaskResponse, error)
	// Queries
	TaskByIssue(context.Context, *TaskByIssueRequest) (*TaskByIssueResponse, error)
	TaskByID(context.Context, *TaskByIDRequest) (*TaskByIDResponse, error)
	OpenPRs(context.Context, *OpenPRsRequest) (*OpenPRsResponse, error)
	ClearTerminalTasks(context.Context, *ClearTerminalTasksRequest) (*ClearTerminalTasksResponse, error)
	Tasks(context.Context, *TasksRequest) (*TasksResponse, error)
	StatusCounts(context.Context, *StatusCountsRequest) (*StatusCountsResponse, error)
	IncrementRetryCount(context.Context, *IncrementRetryCountRequest) (*IncrementRetryCountResponse, error)
	// Events
	InsertEvent(context.Context, *InsertEventRequest) (*InsertEventResponse, error)
	EventsSince(context.Context, *EventsSinceRequest) (*EventsSinceResponse, error)
	TaskEvents(context.Context, *TaskEventsRequest) (*TaskEventsResponse, error)
	WorkflowStats(context.Context, *WorkflowStatsRequest) (*WorkflowStatsResponse, error)
	StageStats(context.Context, *StageStatsRequest) (*StageStatsResponse, error)
	TokensByDay(context.Context, *TokensByDayRequest) (*TokensByDayResponse, error)
	// Configuration snapshot: the running configuration as the dashboard
	// renders it, published by the owner of configuration for the process that
	// displays it. PutConfigSnapshot is administrative; GetConfigSnapshot is
	// the UI's read (docs/architecture/migration-decisions.md, "Dashboard
	// configuration page").
	PutConfigSnapshot(context.Context, *PutConfigSnapshotRequest) (*PutConfigSnapshotResponse, error)
	GetConfigSnapshot(context.Context, *GetConfigSnapshotRequest) (*GetConfigSnapshotResponse, error)
	// Capture
	InsertCapture(context.Context, *InsertCaptureRequest) (*InsertCaptureResponse, error)
	// Deprecated: Do not use.
	// ListCaptures is superseded by StreamCaptures (kept, unmodified, so an
	// in-flight rolling deploy's old client/server pairing keeps working --
	// buf breaking forbids removing or reshaping an existing RPC). Every
	// in-repo caller uses StreamCaptures.
	ListCaptures(context.Context, *ListCapturesRequest) (*ListCapturesResponse, error)
	// StreamCaptures returns one capture per message: a batch of large capture
	// bodies can exceed gRPC's 4MiB unary message cap
	// (docs/prds/state-store-contract.md).
	StreamCaptures(*StreamCapturesRequest, grpc.ServerStreamingServer[StreamCapturesResponse]) error
	// Mapping
	InsertMapping(context.Context, *InsertMappingRequest) (*InsertMappingResponse, error)
	GetMapping(context.Context, *GetMappingRequest) (*GetMappingResponse, error)
	ListMappings(context.Context, *ListMappingsRequest) (*ListMappingsResponse, error)
	UpdateMapping(context.Context, *UpdateMappingRequest) (*UpdateMappingResponse, error)
	DeleteMapping(context.Context, *DeleteMappingRequest) (*DeleteMappingResponse, error)
	// Binding
	InsertBinding(context.Context, *InsertBindingRequest) (*InsertBindingResponse, error)
	GetBinding(context.Context, *GetBindingRequest) (*GetBindingResponse, error)
	ListBindings(context.Context, *ListBindingsRequest) (*ListBindingsResponse, error)
	UpdateBinding(context.Context, *UpdateBindingRequest) (*UpdateBindingResponse, error)
	DeleteBinding(context.Context, *DeleteBindingRequest) (*DeleteBindingResponse, error)
	ApproveBinding(context.Context, *ApproveBindingRequest) (*ApproveBindingResponse, error)
	// Dispatch
	ArmedBindingsForSource(context.Context, *ArmedBindingsForSourceRequest) (*ArmedBindingsForSourceResponse, error)
	RecordDispatch(context.Context, *RecordDispatchRequest) (*RecordDispatchResponse, error)
	// Deprecated: Do not use.
	// ListUndispatchedCaptures is superseded by StreamUndispatchedCaptures; see
	// ListCaptures above.
	ListUndispatchedCaptures(context.Context, *ListUndispatchedCapturesRequest) (*ListUndispatchedCapturesResponse, error)
	StreamUndispatchedCaptures(*StreamUndispatchedCapturesRequest, grpc.ServerStreamingServer[StreamUndispatchedCapturesResponse]) error
	// BindingTaskCreator
	EnqueueBindingTask(context.Context, *EnqueueBindingTaskRequest) (*EnqueueBindingTaskResponse, error)
	mustEmbedUnimplementedStateStoreServiceServer()
}

// UnimplementedStateStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateStoreServiceServer struct{}

func (UnimplementedStateStoreServiceServer) RegisterTaskGrant(context.Context, *RegisterTaskGrantRequest) (*RegisterTaskGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTaskGrant not implemented")
}
func (UnimplementedStateStoreServiceServer) RevokeTaskGrant(context.Context, *RevokeTaskGrantRequest) (*RevokeTaskGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeTaskGrant not implemented")
}
func (UnimplementedStateStoreServiceServer) EnqueueIssue(context.Context, *EnqueueIssueRequest) (*EnqueueIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueIssue not implemented")
}
func (UnimplementedStateStoreServiceServer) EnqueueChatTask(context.Context, *EnqueueChatTaskRequest) (*EnqueueChatTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueChatTask not implemented")
}
func (UnimplementedStateStoreServiceServer) ClaimNext(context.Context, *ClaimNextRequest) (*ClaimNextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimNext not implemented")
}
func (UnimplementedStateStoreServiceServer) ClaimByIssue(context.Context, *ClaimByIssueRequest) (*ClaimByIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimByIssue not implemented")
}
func (UnimplementedStateStoreServiceServer) Transition(context.Context, *TransitionRequest) (*TransitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transition not implemented")
}
func (UnimplementedStateStoreServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedStateStoreServiceServer) Requeue(context.Context, *RequeueRequest) (*RequeueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Requeue not implemented")
}
func (UnimplementedStateStoreServiceServer) RecoverStale(context.Context, *RecoverStaleRequest) (*RecoverStaleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverStale not implemented")
}
func (UnimplementedStateStoreServiceServer) ArchiveTask(context.Context, *ArchiveTaskRequest) (*ArchiveTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveTask not implemented")
}
func (UnimplementedStateStoreServiceServer) RetryTask(context.Context, *RetryTaskRequest) (*RetryTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryTask not implemented")
}
func (UnimplementedStateStoreServiceServer) TaskByIssue(context.Context, *TaskByIssueRequest) (*TaskByIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskByIssue not implemented")
}
func (UnimplementedStateStoreServiceServer) TaskByID(context.Context, *TaskByIDRequest) (*TaskByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskByID not implemented")
}
func (UnimplementedStateStoreServiceServer) OpenPRs(context.Context, *OpenPRsRequest) (*OpenPRsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenPRs not implemented")
}
func (UnimplementedStateStoreServiceServer) ClearTerminalTasks(context.Context, *ClearTerminalTasksRequest) (*ClearTerminalTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearTerminalTasks not implemented")
}
func (UnimplementedStateStoreServiceServer) Tasks(context.Context, *TasksRequest) (*TasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Tasks not implemented")
}
func (UnimplementedStateStoreServiceServer) StatusCounts(context.Context, *StatusCountsRequest) (*StatusCountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StatusCounts not implemented")
}
func (UnimplementedStateStoreServiceServer) IncrementRetryCount(context.Context, *IncrementRetryCountRequest) (*IncrementRetryCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementRetryCount not implemented")
}
func (UnimplementedStateStoreServiceServer) InsertEvent(context.Context, *InsertEventRequest) (*InsertEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertEvent not implemented")
}
func (UnimplementedStateStoreServiceServer) EventsSince(context.Context, *EventsSinceRequest) (*EventsSinceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EventsSince not implemented")
}
func (UnimplementedStateStoreServiceServer) TaskEvents(context.Context, *TaskEventsRequest) (*TaskEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskEvents not implemented")
}
func (UnimplementedStateStoreServiceServer) WorkflowStats(context.Context, *WorkflowStatsRequest) (*WorkflowStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowStats not implemented")
}
func (UnimplementedStateStoreServiceServer) StageStats(context.Context, *StageStatsRequest) (*StageStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StageStats not implemented")
}
func (UnimplementedStateStoreServiceServer) TokensByDay(context.Context, *TokensByDayRequest) (*TokensByDayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TokensByDay not implemented")
}
func (UnimplementedStateStoreServiceServer) PutConfigSnapshot(context.Context, *PutConfigSnapshotRequest) (*PutConfigSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutConfigSnapshot not implemented")
}
func (UnimplementedStateStoreServiceServer) GetConfigSnapshot(context.Context, *GetConfigSnapshotRequest) (*GetConfigSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigSnapshot not implemented")
}
func (UnimplementedStateStoreServiceServer) InsertCapture(context.Context, *InsertCaptureRequest) (*InsertCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertCapture not implemented")
}
func (UnimplementedStateStoreServiceServer) ListCaptures(context.Context, *ListCapturesRequest) (*ListCapturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCaptures not implemented")
}
func (UnimplementedStateStoreServiceServer) StreamCaptures(*StreamCapturesRequest, grpc.ServerStreamingServer[StreamCapturesResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamCaptures not implemented")
}
func (UnimplementedStateStoreServiceServer) InsertMapping(context.Context, *InsertMappingRequest) (*InsertMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertMapping not implemented")
}
func (UnimplementedStateStoreServiceServer) GetMapping(context.Context, *GetMappingRequest) (*GetMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMapping not implemented")
}
func (UnimplementedStateStoreServiceServer) ListMappings(context.Context, *ListMappingsRequest) (*ListMappingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMappings not implemented")
}
func (UnimplementedStateStoreServiceServer) UpdateMapping(context.Context, *UpdateMappingRequest) (*UpdateMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMapping not implemented")
}
func (UnimplementedStateStoreServiceServer) DeleteMapping(context.Context, *DeleteMappingRequest) (*DeleteMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMapping not implemented")
}
func (UnimplementedStateStoreServiceServer) InsertBinding(context.Context, *InsertBindingRequest) (*InsertBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertBinding not implemented")
}
func (UnimplementedStateStoreServiceServer) GetBinding(context.Context, *GetBindingRequest) (*GetBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBinding not implemented")
}
func (UnimplementedStateStoreServiceServer) ListBindings(context.Context, *ListBindingsRequest) (*ListBindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBindings not implemented")
}
func (UnimplementedStateStoreServiceServer) UpdateBinding(context.Context, *UpdateBindingRequest) (*UpdateBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBinding not implemented")
}
func (UnimplementedStateStoreServiceServer) DeleteBinding(context.Context, *DeleteBindingRequest) (*DeleteBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBinding not implemented")
}
func (UnimplementedStateStoreServiceServer) ApproveBinding(context.Context, *ApproveBindingRequest) (*ApproveBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveBinding not implemented")
}
func (UnimplementedStateStoreServiceServer) ArmedBindingsForSource(context.Context, *ArmedBindingsForSourceRequest) (*ArmedBindingsForSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArmedBindingsForSource not implemented")
}
func (UnimplementedStateStoreServiceServer) RecordDispatch(context.Context, *RecordDispatchRequest) (*RecordDispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordDispatch not implemented")
}
func (UnimplementedStateStoreServiceServer) ListUndispatchedCaptures(context.Context, *ListUndispatchedCapturesRequest) (*ListUndispatchedCapturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUndispatchedCaptures not implemented")
}
func (UnimplementedStateStoreServiceServer) StreamUndispatchedCaptures(*StreamUndispatchedCapturesRequest, grpc.ServerStreamingServer[StreamUndispatchedCapturesResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamUndispatchedCaptures not implemented")
}
func (UnimplementedStateStoreServiceServer) EnqueueBindingTask(context.Context, *EnqueueBindingTaskRequest) (*EnqueueBindingTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueBindingTask not implemented")
}
func (UnimplementedStateStoreServiceServer) mustEmbedUnimplementedStateStoreServiceServer() {}
func (UnimplementedStateStoreServiceServer) testEmbeddedByValue()                           {}

// UnsafeStateStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateStoreServiceServer will
// result in compilation errors.
type UnsafeStateStoreServiceServer interface {
	mustEmbedUnimplementedStateStoreServiceServer()
}

func RegisterStateStoreServiceServer(s grpc.ServiceRegistrar, srv StateStoreServiceServer) {
	// If the following call panics, it indicates UnimplementedStateStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateStoreService_ServiceDesc, srv)
}

func _StateStoreService_RegisterTaskGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTaskGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).RegisterTaskGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_RegisterTaskGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).RegisterTaskGrant(ctx, req.(*RegisterTaskGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_RevokeTaskGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTaskGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).RevokeTaskGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_RevokeTaskGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).RevokeTaskGrant(ctx, req.(*RevokeTaskGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_EnqueueIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).EnqueueIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_EnqueueIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).EnqueueIssue(ctx, req.(*EnqueueIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_EnqueueChatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueChatTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).EnqueueChatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_EnqueueChatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).EnqueueChatTask(ctx, req.(*EnqueueChatTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ClaimNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimNextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ClaimNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ClaimNext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ClaimNext(ctx, req.(*ClaimNextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ClaimByIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimByIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ClaimByIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ClaimByIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ClaimByIssue(ctx, req.(*ClaimByIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_Transition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).Transition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_Transition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).Transition(ctx, req.(*TransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_Requeue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequeueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).Requeue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_Requeue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).Requeue(ctx, req.(*RequeueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_RecoverStale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverStaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).RecoverStale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_RecoverStale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).RecoverStale(ctx, req.(*RecoverStaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ArchiveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ArchiveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ArchiveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ArchiveTask(ctx, req.(*ArchiveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_RetryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).RetryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_RetryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).RetryTask(ctx, req.(*RetryTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_TaskByIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskByIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).TaskByIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_TaskByIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).TaskByIssue(ctx, req.(*TaskByIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_TaskByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).TaskByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_TaskByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).TaskByID(ctx, req.(*TaskByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_OpenPRs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPRsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).OpenPRs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_OpenPRs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).OpenPRs(ctx, req.(*OpenPRsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ClearTerminalTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearTerminalTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ClearTerminalTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ClearTerminalTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ClearTerminalTasks(ctx, req.(*ClearTerminalTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_Tasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).Tasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_Tasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).Tasks(ctx, req.(*TasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_StatusCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).StatusCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_StatusCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).StatusCounts(ctx, req.(*StatusCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_IncrementRetryCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementRetryCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).IncrementRetryCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_IncrementRetryCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).IncrementRetryCount(ctx, req.(*IncrementRetryCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_InsertEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).InsertEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_InsertEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).InsertEvent(ctx, req.(*InsertEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_EventsSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventsSinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).EventsSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_EventsSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).EventsSince(ctx, req.(*EventsSinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_TaskEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).TaskEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_TaskEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).TaskEvents(ctx, req.(*TaskEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_WorkflowStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).WorkflowStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_WorkflowStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).WorkflowStats(ctx, req.(*WorkflowStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_StageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).StageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_StageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).StageStats(ctx, req.(*StageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_TokensByDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokensByDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).TokensByDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_TokensByDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).TokensByDay(ctx, req.(*TokensByDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_PutConfigSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutConfigSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).PutConfigSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_PutConfigSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).PutConfigSnapshot(ctx, req.(*PutConfigSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_GetConfigSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).GetConfigSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_GetConfigSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).GetConfigSnapshot(ctx, req.(*GetConfigSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_InsertCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).InsertCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_InsertCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).InsertCapture(ctx, req.(*InsertCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ListCaptures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ListCaptures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ListCaptures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ListCaptures(ctx, req.(*ListCapturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_StreamCaptures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCapturesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateStoreServiceServer).StreamCaptures(m, &grpc.GenericServerStream[StreamCapturesRequest, StreamCapturesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateStoreService_StreamCapturesServer = grpc.ServerStreamingServer[StreamCapturesResponse]

func _StateStoreService_InsertMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).InsertMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_InsertMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).InsertMapping(ctx, req.(*InsertMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_GetMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).GetMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_GetMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).GetMapping(ctx, req.(*GetMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ListMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ListMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ListMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ListMappings(ctx, req.(*ListMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_UpdateMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).UpdateMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_UpdateMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).UpdateMapping(ctx, req.(*UpdateMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_DeleteMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).DeleteMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_DeleteMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).DeleteMapping(ctx, req.(*DeleteMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_InsertBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).InsertBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_InsertBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).InsertBinding(ctx, req.(*InsertBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_GetBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).GetBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_GetBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).GetBinding(ctx, req.(*GetBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ListBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ListBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ListBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ListBindings(ctx, req.(*ListBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_UpdateBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).UpdateBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_UpdateBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).UpdateBinding(ctx, req.(*UpdateBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_DeleteBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).DeleteBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_DeleteBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).DeleteBinding(ctx, req.(*DeleteBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ApproveBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ApproveBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ApproveBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ApproveBinding(ctx, req.(*ApproveBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ArmedBindingsForSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArmedBindingsForSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ArmedBindingsForSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ArmedBindingsForSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ArmedBindingsForSource(ctx, req.(*ArmedBindingsForSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_RecordDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).RecordDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_RecordDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).RecordDispatch(ctx, req.(*RecordDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ListUndispatchedCaptures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUndispatchedCapturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ListUndispatchedCaptures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ListUndispatchedCaptures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ListUndispatchedCaptures(ctx, req.(*ListUndispatchedCapturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_StreamUndispatchedCaptures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamUndispatchedCapturesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StateStoreServiceServer).StreamUndispatchedCaptures(m, &grpc.GenericServerStream[StreamUndispatchedCapturesRequest, StreamUndispatchedCapturesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StateStoreService_StreamUndispatchedCapturesServer = grpc.ServerStreamingServer[StreamUndispatchedCapturesResponse]

func _StateStoreService_EnqueueBindingTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueBindingTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).EnqueueBindingTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_EnqueueBindingTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).EnqueueBindingTask(ctx, req.(*EnqueueBindingTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateStoreService_ServiceDesc is the grpc.ServiceDesc for StateStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "state.v1.StateStoreService",
	HandlerType: (*StateStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTaskGrant",
			Handler:    _StateStoreService_RegisterTaskGrant_Handler,
		},
		{
			MethodName: "RevokeTaskGrant",
			Handler:    _StateStoreService_RevokeTaskGrant_Handler,
		},
		{
			MethodName: "EnqueueIssue",
			Handler:    _StateStoreService_EnqueueIssue_Handler,
		},
		{
			MethodName: "EnqueueChatTask",
			Handler:    _StateStoreService_EnqueueChatTask_Handler,
		},
		{
			MethodName: "ClaimNext",
			Handler:    _StateStoreService_ClaimNext_Handler,
		},
		{
			MethodName: "ClaimByIssue",
			Handler:    _StateStoreService_ClaimByIssue_Handler,
		},
		{
			MethodName: "Transition",
			Handler:    _StateStoreService_Transition_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _StateStoreService_Update_Handler,
		},
		{
			MethodName: "Requeue",
			Handler:    _StateStoreService_Requeue_Handler,
		},
		{
			MethodName: "RecoverStale",
			Handler:    _StateStoreService_RecoverStale_Handler,
		},
		{
			MethodName: "ArchiveTask",
			Handler:    _StateStoreService_ArchiveTask_Handler,
		},
		{
			MethodName: "RetryTask",
			Handler:    _StateStoreService_RetryTask_Handler,
		},
		{
			MethodName: "TaskByIssue",
			Handler:    _StateStoreService_TaskByIssue_Handler,
		},
		{
			MethodName: "TaskByID",
			Handler:    _StateStoreService_TaskByID_Handler,
		},
		{
			MethodName: "OpenPRs",
			Handler:    _StateStoreService_OpenPRs_Handler,
		},
		{
			MethodName: "ClearTerminalTasks",
			Handler:    _StateStoreService_ClearTerminalTasks_Handler,
		},
		{
			MethodName: "Tasks",
			Handler:    _StateStoreService_Tasks_Handler,
		},
		{
			MethodName: "StatusCounts",
			Handler:    _StateStoreService_StatusCounts_Handler,
		},
		{
			MethodName: "IncrementRetryCount",
			Handler:    _StateStoreService_IncrementRetryCount_Handler,
		},
		{
			MethodName: "InsertEvent",
			Handler:    _StateStoreService_InsertEvent_Handler,
		},
		{
			MethodName: "EventsSince",
			Handler:    _StateStoreService_EventsSince_Handler,
		},
		{
			MethodName: "TaskEvents",
			Handler:    _StateStoreService_TaskEvents_Handler,
		},
		{
			MethodName: "WorkflowStats",
			Handler:    _StateStoreService_WorkflowStats_Handler,
		},
		{
			MethodName: "StageStats",
			Handler:    _StateStoreService_StageStats_Handler,
		},
		{
			MethodName: "TokensByDay",
			Handler:    _StateStoreService_TokensByDay_Handler,
		},
		{
			MethodName: "PutConfigSnapshot",
			Handler:    _StateStoreService_PutConfigSnapshot_Handler,
		},
		{
			MethodName: "GetConfigSnapshot",
			Handler:    _StateStoreService_GetConfigSnapshot_Handler,
		},
		{
			MethodName: "InsertCapture",
			Handler:    _StateStoreService_InsertCapture_Handler,
		},
		{
			MethodName: "ListCaptures",
			Handler:    _StateStoreService_ListCaptures_Handler,
		},
		{
			MethodName: "InsertMapping",
			Handler:    _StateStoreService_InsertMapping_Handler,
		},
		{
			MethodName: "GetMapping",
			Handler:    _StateStoreService_GetMapping_Handler,
		},
		{
			MethodName: "ListMappings",
			Handler:    _StateStoreService_ListMappings_Handler,
		},
		{
			MethodName: "UpdateMapping",
			Handler:    _StateStoreService_UpdateMapping_Handler,
		},
		{
			MethodName: "DeleteMapping",
			Handler:    _StateStoreService_DeleteMapping_Handler,
		},
		{
			MethodName: "InsertBinding",
			Handler:    _StateStoreService_InsertBinding_Handler,
		},
		{
			MethodName: "GetBinding",
			Handler:    _StateStoreService_GetBinding_Handler,
		},
		{
			MethodName: "ListBindings",
			Handler:    _StateStoreService_ListBindings_Handler,
		},
		{
			MethodName: "UpdateBinding",
			Handler:    _StateStoreService_UpdateBinding_Handler,
		},
		{
			MethodName: "DeleteBinding",
			Handler:    _StateStoreService_DeleteBinding_Handler,
		},
		{
			MethodName: "ApproveBinding",
			Handler:    _StateStoreService_ApproveBinding_Handler,
		},
		{
			MethodName: "ArmedBindingsForSource",
			Handler:    _StateStoreService_ArmedBindingsForSource_Handler,
		},
		{
			MethodName: "RecordDispatch",
			Handler:    _StateStoreService_RecordDispatch_Handler,
		},
		{
			MethodName: "ListUndispatchedCaptures",
			Handler:    _StateStoreService_ListUndispatchedCaptures_Handler,
		},
		{
			MethodName: "EnqueueBindingTask",
			Handler:    _StateStoreService_EnqueueBindingTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCaptures",
			Handler:       _StateStoreService_StreamCaptures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamUndispatchedCaptures",
			Handler:       _StateStoreService_StreamUndispatchedCaptures_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "state/v1/state.proto",
}
