// Package log is the schema source for the "log" Module action kind -- the
// side-effect-free proof-of-concept kind for the Module position (t2db.13,
// docs/prds/module-position.md). A Yaegi module implementing this kind
// exports a fixed function name against these generated types; the operator's
// file is the implementation, this package is the contract.
//
// This is the hand-written schema. logextract (generated by `go generate`)
// turns it into the Yaegi symbol table the interpreter uses.
package log

// SchemaVersion is independent of a playbook's own workflow_version, per
// eda-playbook-engine.md's schema-versioning point.
const SchemaVersion = 1

// Args is the accepted message shape for the log kind. Invoke decodes the
// playbook's args map into this struct before calling the interpreted
// function; a shape mismatch is a reported failure, not a silent zero fill.
type Args struct {
	// Message is the line to write to the daemon's log. Required.
	Message string
	// Level is optional; the implementation may default it.
	Level string
}

// Result is what the log kind returns. It is surfaced as map[string]any so a
// later data-flow mechanism can use it (module-position.md open question 3).
type Result struct {
	// Written reports whether the implementation wrote the line.
	Written bool
	// Level echoes the level actually used.
	Level string
}
