// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateway/v1/chat.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Platform        string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	BotUser         string                 `protobuf:"bytes,3,opt,name=bot_user,json=botUser,proto3" json:"bot_user,omitempty"`
	ChannelId       string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ThreadId        string                 `protobuf:"bytes,5,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Title           string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	ParentSessionId string                 `protobuf:"bytes,7,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	BranchName      string                 `protobuf:"bytes,8,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActiveAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_gateway_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Session) GetBotUser() string {
	if x != nil {
		return x.BotUser
	}
	return ""
}

func (x *Session) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Session) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *Session) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetLastActiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActiveAt
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,4,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	From          string                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Page          string                 `protobuf:"bytes,7,opt,name=page,proto3" json:"page,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_gateway_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Message) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Message) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *Message) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Parameters    string                 `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_gateway_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

func (x *ToolCall) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolCall) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	FileId        string                 `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileName      string                 `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      *int64                 `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3,oneof" json:"file_size,omitempty"`
	Width         *int64                 `protobuf:"varint,9,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height        *int64                 `protobuf:"varint,10,opt,name=height,proto3,oneof" json:"height,omitempty"`
	Duration      *int64                 `protobuf:"varint,11,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_gateway_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *Media) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Media) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Media) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Media) GetFileSize() int64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *Media) GetWidth() int64 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Media) GetHeight() int64 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *Media) GetDuration() int64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

type Turn struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TurnId             string                 `protobuf:"bytes,1,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	SessionId          string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SourceId           string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Attempt            int64                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	OwnerId            string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	InputMessageId     string                 `protobuf:"bytes,7,opt,name=input_message_id,json=inputMessageId,proto3" json:"input_message_id,omitempty"`
	AssistantMessageId string                 `protobuf:"bytes,8,opt,name=assistant_message_id,json=assistantMessageId,proto3" json:"assistant_message_id,omitempty"`
	PartialText        string                 `protobuf:"bytes,9,opt,name=partial_text,json=partialText,proto3" json:"partial_text,omitempty"`
	ResponseText       string                 `protobuf:"bytes,10,opt,name=response_text,json=responseText,proto3" json:"response_text,omitempty"`
	ToolCalls          []*ToolCall            `protobuf:"bytes,11,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Error              string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_gateway_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *Turn) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *Turn) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Turn) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Turn) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Turn) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Turn) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Turn) GetInputMessageId() string {
	if x != nil {
		return x.InputMessageId
	}
	return ""
}

func (x *Turn) GetAssistantMessageId() string {
	if x != nil {
		return x.AssistantMessageId
	}
	return ""
}

func (x *Turn) GetPartialText() string {
	if x != nil {
		return x.PartialText
	}
	return ""
}

func (x *Turn) GetResponseText() string {
	if x != nil {
		return x.ResponseText
	}
	return ""
}

func (x *Turn) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Turn) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Turn) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Turn) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_gateway_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_gateway_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{6}
}

type SnapshotResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Sessions              []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Models                []string               `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	ModelsByProvider      map[string]*StringList `protobuf:"bytes,3,rep,name=models_by_provider,json=modelsByProvider,proto3" json:"models_by_provider,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Providers             []string               `protobuf:"bytes,4,rep,name=providers,proto3" json:"providers,omitempty"`
	ActiveModel           string                 `protobuf:"bytes,5,opt,name=active_model,json=activeModel,proto3" json:"active_model,omitempty"`
	ActiveProvider        string                 `protobuf:"bytes,6,opt,name=active_provider,json=activeProvider,proto3" json:"active_provider,omitempty"`
	Personas              []string               `protobuf:"bytes,7,rep,name=personas,proto3" json:"personas,omitempty"`
	ActivePersonas        map[string]string      `protobuf:"bytes,8,rep,name=active_personas,json=activePersonas,proto3" json:"active_personas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RestartAvailable      bool                   `protobuf:"varint,9,opt,name=restart_available,json=restartAvailable,proto3" json:"restart_available,omitempty"`
	CancellationAvailable bool                   `protobuf:"varint,10,opt,name=cancellation_available,json=cancellationAvailable,proto3" json:"cancellation_available,omitempty"`
	PersonasAvailable     bool                   `protobuf:"varint,11,opt,name=personas_available,json=personasAvailable,proto3" json:"personas_available,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_gateway_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *SnapshotResponse) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *SnapshotResponse) GetModelsByProvider() map[string]*StringList {
	if x != nil {
		return x.ModelsByProvider
	}
	return nil
}

func (x *SnapshotResponse) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *SnapshotResponse) GetActiveModel() string {
	if x != nil {
		return x.ActiveModel
	}
	return ""
}

func (x *SnapshotResponse) GetActiveProvider() string {
	if x != nil {
		return x.ActiveProvider
	}
	return ""
}

func (x *SnapshotResponse) GetPersonas() []string {
	if x != nil {
		return x.Personas
	}
	return nil
}

func (x *SnapshotResponse) GetActivePersonas() map[string]string {
	if x != nil {
		return x.ActivePersonas
	}
	return nil
}

func (x *SnapshotResponse) GetRestartAvailable() bool {
	if x != nil {
		return x.RestartAvailable
	}
	return false
}

func (x *SnapshotResponse) GetCancellationAvailable() bool {
	if x != nil {
		return x.CancellationAvailable
	}
	return false
}

func (x *SnapshotResponse) GetPersonasAvailable() bool {
	if x != nil {
		return x.PersonasAvailable
	}
	return false
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_gateway_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_gateway_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetSessionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type RecentMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentMessagesRequest) Reset() {
	*x = RecentMessagesRequest{}
	mi := &file_gateway_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentMessagesRequest) ProtoMessage() {}

func (x *RecentMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentMessagesRequest.ProtoReflect.Descriptor instead.
func (*RecentMessagesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *RecentMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecentMessagesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentMessagesResponse) Reset() {
	*x = RecentMessagesResponse{}
	mi := &file_gateway_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentMessagesResponse) ProtoMessage() {}

func (x *RecentMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentMessagesResponse.ProtoReflect.Descriptor instead.
func (*RecentMessagesResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *RecentMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type RecentTurnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentTurnsRequest) Reset() {
	*x = RecentTurnsRequest{}
	mi := &file_gateway_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentTurnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentTurnsRequest) ProtoMessage() {}

func (x *RecentTurnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentTurnsRequest.ProtoReflect.Descriptor instead.
func (*RecentTurnsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *RecentTurnsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecentTurnsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentTurnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turns         []*Turn                `protobuf:"bytes,1,rep,name=turns,proto3" json:"turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentTurnsResponse) Reset() {
	*x = RecentTurnsResponse{}
	mi := &file_gateway_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentTurnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentTurnsResponse) ProtoMessage() {}

func (x *RecentTurnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentTurnsResponse.ProtoReflect.Descriptor instead.
func (*RecentTurnsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *RecentTurnsResponse) GetTurns() []*Turn {
	if x != nil {
		return x.Turns
	}
	return nil
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_gateway_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{14}
}

func (x *RouteRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_gateway_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *RouteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RouteResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_gateway_v1_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{16}
}

func (x *StreamRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tool          *ToolCall              `protobuf:"bytes,4,opt,name=tool,proto3" json:"tool,omitempty"`
	Media         *Media                 `protobuf:"bytes,5,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_gateway_v1_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{17}
}

func (x *StreamResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StreamResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StreamResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamResponse) GetTool() *ToolCall {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *StreamResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_gateway_v1_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{18}
}

func (x *CancelRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Dropped       int64                  `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_gateway_v1_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{19}
}

func (x *CancelResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelResponse) GetDropped() int64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

type SetPersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPersonaRequest) Reset() {
	*x = SetPersonaRequest{}
	mi := &file_gateway_v1_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPersonaRequest) ProtoMessage() {}

func (x *SetPersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPersonaRequest.ProtoReflect.Descriptor instead.
func (*SetPersonaRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{20}
}

func (x *SetPersonaRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetPersonaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetPersonaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPersonaResponse) Reset() {
	*x = SetPersonaResponse{}
	mi := &file_gateway_v1_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPersonaResponse) ProtoMessage() {}

func (x *SetPersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPersonaResponse.ProtoReflect.Descriptor instead.
func (*SetPersonaResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{21}
}

func (x *SetPersonaResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ApplyTaskActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyTaskActionRequest) Reset() {
	*x = ApplyTaskActionRequest{}
	mi := &file_gateway_v1_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTaskActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTaskActionRequest) ProtoMessage() {}

func (x *ApplyTaskActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTaskActionRequest.ProtoReflect.Descriptor instead.
func (*ApplyTaskActionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{22}
}

func (x *ApplyTaskActionRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ApplyTaskActionRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ApplyTaskActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ApplyTaskActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyTaskActionResponse) Reset() {
	*x = ApplyTaskActionResponse{}
	mi := &file_gateway_v1_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTaskActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTaskActionResponse) ProtoMessage() {}

func (x *ApplyTaskActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTaskActionResponse.ProtoReflect.Descriptor instead.
func (*ApplyTaskActionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_chat_proto_rawDescGZIP(), []int{23}
}

func (x *ApplyTaskActionResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ApplyTaskActionResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ApplyTaskActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gateway_v1_chat_proto protoreflect.FileDescriptor

const file_gateway_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x15gateway/v1/chat.proto\x12\n" +
	"gateway.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x02\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x19\n" +
	"\bbot_user\x18\x03 \x01(\tR\abotUser\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tthread_id\x18\x05 \x01(\tR\bthreadId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12*\n" +
	"\x11parent_session_id\x18\a \x01(\tR\x0fparentSessionId\x12\x1f\n" +
	"\vbranch_name\x18\b \x01(\tR\n" +
	"branchName\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\x0elast_active_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\flastActiveAt\"\xe9\x01\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tthread_id\x18\x04 \x01(\tR\bthreadId\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x12\n" +
	"\x04page\x18\a \x01(\tR\x04page\x12*\n" +
	"\x02at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"|\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xdc\x02\n" +
	"\x05Media\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\tR\x06fileId\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\x12 \n" +
	"\tfile_size\x18\b \x01(\x03H\x00R\bfileSize\x88\x01\x01\x12\x19\n" +
	"\x05width\x18\t \x01(\x03H\x01R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\n" +
	" \x01(\x03H\x02R\x06height\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\v \x01(\x03H\x03R\bduration\x88\x01\x01B\f\n" +
	"\n" +
	"_file_sizeB\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\v\n" +
	"\t_duration\"\x8d\x04\n" +
	"\x04Turn\x12\x17\n" +
	"\aturn_id\x18\x01 \x01(\tR\x06turnId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x03R\aattempt\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12(\n" +
	"\x10input_message_id\x18\a \x01(\tR\x0einputMessageId\x120\n" +
	"\x14assistant_message_id\x18\b \x01(\tR\x12assistantMessageId\x12!\n" +
	"\fpartial_text\x18\t \x01(\tR\vpartialText\x12#\n" +
	"\rresponse_text\x18\n" +
	" \x01(\tR\fresponseText\x123\n" +
	"\n" +
	"tool_calls\x18\v \x03(\v2\x14.gateway.v1.ToolCallR\ttoolCalls\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x11\n" +
	"\x0fSnapshotRequest\"\xd1\x05\n" +
	"\x10SnapshotResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.gateway.v1.SessionR\bsessions\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\x12`\n" +
	"\x12models_by_provider\x18\x03 \x03(\v22.gateway.v1.SnapshotResponse.ModelsByProviderEntryR\x10modelsByProvider\x12\x1c\n" +
	"\tproviders\x18\x04 \x03(\tR\tproviders\x12!\n" +
	"\factive_model\x18\x05 \x01(\tR\vactiveModel\x12'\n" +
	"\x0factive_provider\x18\x06 \x01(\tR\x0eactiveProvider\x12\x1a\n" +
	"\bpersonas\x18\a \x03(\tR\bpersonas\x12Y\n" +
	"\x0factive_personas\x18\b \x03(\v20.gateway.v1.SnapshotResponse.ActivePersonasEntryR\x0eactivePersonas\x12+\n" +
	"\x11restart_available\x18\t \x01(\bR\x10restartAvailable\x125\n" +
	"\x16cancellation_available\x18\n" +
	" \x01(\bR\x15cancellationAvailable\x12-\n" +
	"\x12personas_available\x18\v \x01(\bR\x11personasAvailable\x1a[\n" +
	"\x15ModelsByProviderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.gateway.v1.StringListR\x05value:\x028\x01\x1aA\n" +
	"\x13ActivePersonasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"Y\n" +
	"\x12GetSessionResponse\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.gateway.v1.SessionR\asession\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"L\n" +
	"\x15RecentMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"I\n" +
	"\x16RecentMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.gateway.v1.MessageR\bmessages\"I\n" +
	"\x12RecentTurnsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"=\n" +
	"\x13RecentTurnsResponse\x12&\n" +
	"\x05turns\x18\x01 \x03(\v2\x10.gateway.v1.TurnR\x05turns\"=\n" +
	"\fRouteRequest\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.gateway.v1.MessageR\amessage\"B\n" +
	"\rRouteResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\">\n" +
	"\rStreamRequest\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.gateway.v1.MessageR\amessage\"\xaa\x01\n" +
	"\x0eStreamResponse\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12(\n" +
	"\x04tool\x18\x04 \x01(\v2\x14.gateway.v1.ToolCallR\x04tool\x12'\n" +
	"\x05media\x18\x05 \x01(\v2\x11.gateway.v1.MediaR\x05media\".\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"H\n" +
	"\x0eCancelResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\x12\x18\n" +
	"\adropped\x18\x02 \x01(\x03R\adropped\"F\n" +
	"\x11SetPersonaRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x12SetPersonaResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\"e\n" +
	"\x16ApplyTaskActionRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"d\n" +
	"\x17ApplyTaskActionResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xb5\x05\n" +
	"\vChatService\x12E\n" +
	"\bSnapshot\x12\x1b.gateway.v1.SnapshotRequest\x1a\x1c.gateway.v1.SnapshotResponse\x12K\n" +
	"\n" +
	"GetSession\x12\x1d.gateway.v1.GetSessionRequest\x1a\x1e.gateway.v1.GetSessionResponse\x12W\n" +
	"\x0eRecentMessages\x12!.gateway.v1.RecentMessagesRequest\x1a\".gateway.v1.RecentMessagesResponse\x12N\n" +
	"\vRecentTurns\x12\x1e.gateway.v1.RecentTurnsRequest\x1a\x1f.gateway.v1.RecentTurnsResponse\x12<\n" +
	"\x05Route\x12\x18.gateway.v1.RouteRequest\x1a\x19.gateway.v1.RouteResponse\x12A\n" +
	"\x06Stream\x12\x19.gateway.v1.StreamRequest\x1a\x1a.gateway.v1.StreamResponse0\x01\x12?\n" +
	"\x06Cancel\x12\x19.gateway.v1.CancelRequest\x1a\x1a.gateway.v1.CancelResponse\x12K\n" +
	"\n" +
	"SetPersona\x12\x1d.gateway.v1.SetPersonaRequest\x1a\x1e.gateway.v1.SetPersonaResponse\x12Z\n" +
	"\x0fApplyTaskAction\x12\".gateway.v1.ApplyTaskActionRequest\x1a#.gateway.v1.ApplyTaskActionResponseB\xb1\x01\n" +
	"\x0ecom.gateway.v1B\tChatProtoP\x01ZKgithub.com/samcharles93/archie-core/internal/contracts/gateway/v1;gatewayv1\xa2\x02\x03GXX\xaa\x02\n" +
	"Gateway.V1\xca\x02\n" +
	"Gateway\\V1\xe2\x02\x16Gateway\\V1\\GPBMetadata\xea\x02\vGateway::V1b\x06proto3"

var (
	file_gateway_v1_chat_proto_rawDescOnce sync.Once
	file_gateway_v1_chat_proto_rawDescData []byte
)

func file_gateway_v1_chat_proto_rawDescGZIP() []byte {
	file_gateway_v1_chat_proto_rawDescOnce.Do(func() {
		file_gateway_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_chat_proto_rawDesc), len(file_gateway_v1_chat_proto_rawDesc)))
	})
	return file_gateway_v1_chat_proto_rawDescData
}

var file_gateway_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_gateway_v1_chat_proto_goTypes = []any{
	(*Session)(nil),                 // 0: gateway.v1.Session
	(*Message)(nil),                 // 1: gateway.v1.Message
	(*ToolCall)(nil),                // 2: gateway.v1.ToolCall
	(*Media)(nil),                   // 3: gateway.v1.Media
	(*Turn)(nil),                    // 4: gateway.v1.Turn
	(*StringList)(nil),              // 5: gateway.v1.StringList
	(*SnapshotRequest)(nil),         // 6: gateway.v1.SnapshotRequest
	(*SnapshotResponse)(nil),        // 7: gateway.v1.SnapshotResponse
	(*GetSessionRequest)(nil),       // 8: gateway.v1.GetSessionRequest
	(*GetSessionResponse)(nil),      // 9: gateway.v1.GetSessionResponse
	(*RecentMessagesRequest)(nil),   // 10: gateway.v1.RecentMessagesRequest
	(*RecentMessagesResponse)(nil),  // 11: gateway.v1.RecentMessagesResponse
	(*RecentTurnsRequest)(nil),      // 12: gateway.v1.RecentTurnsRequest
	(*RecentTurnsResponse)(nil),     // 13: gateway.v1.RecentTurnsResponse
	(*RouteRequest)(nil),            // 14: gateway.v1.RouteRequest
	(*RouteResponse)(nil),           // 15: gateway.v1.RouteResponse
	(*StreamRequest)(nil),           // 16: gateway.v1.StreamRequest
	(*StreamResponse)(nil),          // 17: gateway.v1.StreamResponse
	(*CancelRequest)(nil),           // 18: gateway.v1.CancelRequest
	(*CancelResponse)(nil),          // 19: gateway.v1.CancelResponse
	(*SetPersonaRequest)(nil),       // 20: gateway.v1.SetPersonaRequest
	(*SetPersonaResponse)(nil),      // 21: gateway.v1.SetPersonaResponse
	(*ApplyTaskActionRequest)(nil),  // 22: gateway.v1.ApplyTaskActionRequest
	(*ApplyTaskActionResponse)(nil), // 23: gateway.v1.ApplyTaskActionResponse
	nil,                             // 24: gateway.v1.SnapshotResponse.ModelsByProviderEntry
	nil,                             // 25: gateway.v1.SnapshotResponse.ActivePersonasEntry
	(*timestamppb.Timestamp)(nil),   // 26: google.protobuf.Timestamp
}
var file_gateway_v1_chat_proto_depIdxs = []int32{
	26, // 0: gateway.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	26, // 1: gateway.v1.Session.last_active_at:type_name -> google.protobuf.Timestamp
	26, // 2: gateway.v1.Message.at:type_name -> google.protobuf.Timestamp
	2,  // 3: gateway.v1.Turn.tool_calls:type_name -> gateway.v1.ToolCall
	26, // 4: gateway.v1.Turn.created_at:type_name -> google.protobuf.Timestamp
	26, // 5: gateway.v1.Turn.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: gateway.v1.SnapshotResponse.sessions:type_name -> gateway.v1.Session
	24, // 7: gateway.v1.SnapshotResponse.models_by_provider:type_name -> gateway.v1.SnapshotResponse.ModelsByProviderEntry
	25, // 8: gateway.v1.SnapshotResponse.active_personas:type_name -> gateway.v1.SnapshotResponse.ActivePersonasEntry
	0,  // 9: gateway.v1.GetSessionResponse.session:type_name -> gateway.v1.Session
	1,  // 10: gateway.v1.RecentMessagesResponse.messages:type_name -> gateway.v1.Message
	4,  // 11: gateway.v1.RecentTurnsResponse.turns:type_name -> gateway.v1.Turn
	1,  // 12: gateway.v1.RouteRequest.message:type_name -> gateway.v1.Message
	1,  // 13: gateway.v1.StreamRequest.message:type_name -> gateway.v1.Message
	2,  // 14: gateway.v1.StreamResponse.tool:type_name -> gateway.v1.ToolCall
	3,  // 15: gateway.v1.StreamResponse.media:type_name -> gateway.v1.Media
	5,  // 16: gateway.v1.SnapshotResponse.ModelsByProviderEntry.value:type_name -> gateway.v1.StringList
	6,  // 17: gateway.v1.ChatService.Snapshot:input_type -> gateway.v1.SnapshotRequest
	8,  // 18: gateway.v1.ChatService.GetSession:input_type -> gateway.v1.GetSessionRequest
	10, // 19: gateway.v1.ChatService.RecentMessages:input_type -> gateway.v1.RecentMessagesRequest
	12, // 20: gateway.v1.ChatService.RecentTurns:input_type -> gateway.v1.RecentTurnsRequest
	14, // 21: gateway.v1.ChatService.Route:input_type -> gateway.v1.RouteRequest
	16, // 22: gateway.v1.ChatService.Stream:input_type -> gateway.v1.StreamRequest
	18, // 23: gateway.v1.ChatService.Cancel:input_type -> gateway.v1.CancelRequest
	20, // 24: gateway.v1.ChatService.SetPersona:input_type -> gateway.v1.SetPersonaRequest
	22, // 25: gateway.v1.ChatService.ApplyTaskAction:input_type -> gateway.v1.ApplyTaskActionRequest
	7,  // 26: gateway.v1.ChatService.Snapshot:output_type -> gateway.v1.SnapshotResponse
	9,  // 27: gateway.v1.ChatService.GetSession:output_type -> gateway.v1.GetSessionResponse
	11, // 28: gateway.v1.ChatService.RecentMessages:output_type -> gateway.v1.RecentMessagesResponse
	13, // 29: gateway.v1.ChatService.RecentTurns:output_type -> gateway.v1.RecentTurnsResponse
	15, // 30: gateway.v1.ChatService.Route:output_type -> gateway.v1.RouteResponse
	17, // 31: gateway.v1.ChatService.Stream:output_type -> gateway.v1.StreamResponse
	19, // 32: gateway.v1.ChatService.Cancel:output_type -> gateway.v1.CancelResponse
	21, // 33: gateway.v1.ChatService.SetPersona:output_type -> gateway.v1.SetPersonaResponse
	23, // 34: gateway.v1.ChatService.ApplyTaskAction:output_type -> gateway.v1.ApplyTaskActionResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_gateway_v1_chat_proto_init() }
func file_gateway_v1_chat_proto_init() {
	if File_gateway_v1_chat_proto != nil {
		return
	}
	file_gateway_v1_chat_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_chat_proto_rawDesc), len(file_gateway_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_chat_proto_goTypes,
		DependencyIndexes: file_gateway_v1_chat_proto_depIdxs,
		MessageInfos:      file_gateway_v1_chat_proto_msgTypes,
	}.Build()
	File_gateway_v1_chat_proto = out.File
	file_gateway_v1_chat_proto_goTypes = nil
	file_gateway_v1_chat_proto_depIdxs = nil
}
