// Package gateextract holds the Yaegi symbol table for internal/gate,
// generated by `go generate`. Kept separate from internal/gate itself so
// the generated file can import it without a self-import cycle.
package gateextract

import "reflect"

//go:generate go run github.com/traefik/yaegi/cmd/yaegi extract -name gateextract github.com/samcharles93/archie-core/internal/gate

var Symbols = map[string]map[string]reflect.Value{}
