// Code generated by 'yaegi extract github.com/samcharles93/archie-core/internal/gate'. DO NOT EDIT.

package gateextract

import (
	"reflect"

	"github.com/samcharles93/archie-core/internal/gate"
)

func init() {
	Symbols["github.com/samcharles93/archie-core/internal/gate/gate"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Blocking": reflect.ValueOf(gate.Blocking),

		// type definitions
		"Finding":     reflect.ValueOf((*gate.Finding)(nil)),
		"GateContext": reflect.ValueOf((*gate.GateContext)(nil)),
	}
}
