// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: logging/v1/logging.proto

package loggingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Levels        []string               `protobuf:"bytes,2,rep,name=levels,proto3" json:"levels,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Contains      string                 `protobuf:"bytes,4,opt,name=contains,proto3" json:"contains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogQuery) Reset() {
	*x = LogQuery{}
	mi := &file_logging_v1_logging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogQuery) ProtoMessage() {}

func (x *LogQuery) ProtoReflect() protoreflect.Message {
	mi := &file_logging_v1_logging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogQuery.ProtoReflect.Descriptor instead.
func (*LogQuery) Descriptor() ([]byte, []int) {
	return file_logging_v1_logging_proto_rawDescGZIP(), []int{0}
}

func (x *LogQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LogQuery) GetLevels() []string {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *LogQuery) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LogQuery) GetContains() string {
	if x != nil {
		return x.Contains
	}
	return ""
}

type LogSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntriesJson   []byte                 `protobuf:"bytes,1,opt,name=entries_json,json=entriesJson,proto3" json:"entries_json,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSnapshot) Reset() {
	*x = LogSnapshot{}
	mi := &file_logging_v1_logging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSnapshot) ProtoMessage() {}

func (x *LogSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_logging_v1_logging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSnapshot.ProtoReflect.Descriptor instead.
func (*LogSnapshot) Descriptor() ([]byte, []int) {
	return file_logging_v1_logging_proto_rawDescGZIP(), []int{1}
}

func (x *LogSnapshot) GetEntriesJson() []byte {
	if x != nil {
		return x.EntriesJson
	}
	return nil
}

func (x *LogSnapshot) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_logging_v1_logging_proto protoreflect.FileDescriptor

const file_logging_v1_logging_proto_rawDesc = "" +
	"\n" +
	"\x18logging/v1/logging.proto\x12\n" +
	"logging.v1\"r\n" +
	"\bLogQuery\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06levels\x18\x02 \x03(\tR\x06levels\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x1a\n" +
	"\bcontains\x18\x04 \x01(\tR\bcontains\"N\n" +
	"\vLogSnapshot\x12!\n" +
	"\fentries_json\x18\x01 \x01(\fR\ventriesJson\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncatedB\xb4\x01\n" +
	"\x0ecom.logging.v1B\fLoggingProtoP\x01ZKgithub.com/samcharles93/archie-core/internal/contracts/logging/v1;loggingv1\xa2\x02\x03LXX\xaa\x02\n" +
	"Logging.V1\xca\x02\n" +
	"Logging\\V1\xe2\x02\x16Logging\\V1\\GPBMetadata\xea\x02\vLogging::V1b\x06proto3"

var (
	file_logging_v1_logging_proto_rawDescOnce sync.Once
	file_logging_v1_logging_proto_rawDescData []byte
)

func file_logging_v1_logging_proto_rawDescGZIP() []byte {
	file_logging_v1_logging_proto_rawDescOnce.Do(func() {
		file_logging_v1_logging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logging_v1_logging_proto_rawDesc), len(file_logging_v1_logging_proto_rawDesc)))
	})
	return file_logging_v1_logging_proto_rawDescData
}

var file_logging_v1_logging_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logging_v1_logging_proto_goTypes = []any{
	(*LogQuery)(nil),    // 0: logging.v1.LogQuery
	(*LogSnapshot)(nil), // 1: logging.v1.LogSnapshot
}
var file_logging_v1_logging_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logging_v1_logging_proto_init() }
func file_logging_v1_logging_proto_init() {
	if File_logging_v1_logging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logging_v1_logging_proto_rawDesc), len(file_logging_v1_logging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logging_v1_logging_proto_goTypes,
		DependencyIndexes: file_logging_v1_logging_proto_depIdxs,
		MessageInfos:      file_logging_v1_logging_proto_msgTypes,
	}.Build()
	File_logging_v1_logging_proto = out.File
	file_logging_v1_logging_proto_goTypes = nil
	file_logging_v1_logging_proto_depIdxs = nil
}
