// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package postgresdb

import (
	"context"
)

const importCompleted = `-- name: ImportCompleted :one
SELECT EXISTS (SELECT 1 FROM import_completion)
`

func (q *Queries) ImportCompleted(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, importCompleted)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertFreshInstallCompletion = `-- name: InsertFreshInstallCompletion :exec
INSERT INTO import_completion (id, sources, report) VALUES (1, '', 'fresh install: no legacy data')
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) InsertFreshInstallCompletion(ctx context.Context) error {
	_, err := q.db.Exec(ctx, insertFreshInstallCompletion)
	return err
}

const insertImportCompletion = `-- name: InsertImportCompletion :exec

INSERT INTO import_completion (id, sources, report) VALUES (1, $1, $2)
`

type InsertImportCompletionParams struct {
	Sources string
	Report  string
}

// The one-time legacy import's completion record.
func (q *Queries) InsertImportCompletion(ctx context.Context, arg InsertImportCompletionParams) error {
	_, err := q.db.Exec(ctx, insertImportCompletion, arg.Sources, arg.Report)
	return err
}
