// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installed_packages.sql

package postgresdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInstalledPackageAuthority = `-- name: AcceptInstalledPackageAuthority :execrows
UPDATE installed_packages SET accepted_authority = $3
WHERE org_id = $1 AND name = $2
`

type AcceptInstalledPackageAuthorityParams struct {
	OrgID             string
	Name              string
	AcceptedAuthority []byte
}

func (q *Queries) AcceptInstalledPackageAuthority(ctx context.Context, arg AcceptInstalledPackageAuthorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInstalledPackageAuthority, arg.OrgID, arg.Name, arg.AcceptedAuthority)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countInstalledDependents = `-- name: CountInstalledDependents :one
SELECT count(*) FROM installed_package_requirements WHERE org_id = $1 AND required_name = $2
`

type CountInstalledDependentsParams struct {
	OrgID        string
	RequiredName string
}

func (q *Queries) CountInstalledDependents(ctx context.Context, arg CountInstalledDependentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInstalledDependents, arg.OrgID, arg.RequiredName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteInstalledPackage = `-- name: DeleteInstalledPackage :execrows
DELETE FROM installed_packages WHERE org_id = $1 AND name = $2
`

type DeleteInstalledPackageParams struct {
	OrgID string
	Name  string
}

func (q *Queries) DeleteInstalledPackage(ctx context.Context, arg DeleteInstalledPackageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstalledPackage, arg.OrgID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInstalledRequirements = `-- name: DeleteInstalledRequirements :exec
DELETE FROM installed_package_requirements WHERE org_id = $1 AND package_name = $2
`

type DeleteInstalledRequirementsParams struct {
	OrgID       string
	PackageName string
}

func (q *Queries) DeleteInstalledRequirements(ctx context.Context, arg DeleteInstalledRequirementsParams) error {
	_, err := q.db.Exec(ctx, deleteInstalledRequirements, arg.OrgID, arg.PackageName)
	return err
}

const getInstalledPackage = `-- name: GetInstalledPackage :one
SELECT org_id, name, reference, digest, descriptor, layer, update_policy, accepted_authority,
    pending_reference, pending_digest, pending_authority, previous_reference, previous_digest, previous_accepted_authority
FROM installed_packages WHERE org_id = $1 AND name = $2
`

type GetInstalledPackageParams struct {
	OrgID string
	Name  string
}

type GetInstalledPackageRow struct {
	OrgID                     string
	Name                      string
	Reference                 string
	Digest                    string
	Descriptor                []byte
	Layer                     []byte
	UpdatePolicy              string
	AcceptedAuthority         []byte
	PendingReference          pgtype.Text
	PendingDigest             pgtype.Text
	PendingAuthority          []byte
	PreviousReference         pgtype.Text
	PreviousDigest            pgtype.Text
	PreviousAcceptedAuthority []byte
}

func (q *Queries) GetInstalledPackage(ctx context.Context, arg GetInstalledPackageParams) (GetInstalledPackageRow, error) {
	row := q.db.QueryRow(ctx, getInstalledPackage, arg.OrgID, arg.Name)
	var i GetInstalledPackageRow
	err := row.Scan(
		&i.OrgID,
		&i.Name,
		&i.Reference,
		&i.Digest,
		&i.Descriptor,
		&i.Layer,
		&i.UpdatePolicy,
		&i.AcceptedAuthority,
		&i.PendingReference,
		&i.PendingDigest,
		&i.PendingAuthority,
		&i.PreviousReference,
		&i.PreviousDigest,
		&i.PreviousAcceptedAuthority,
	)
	return i, err
}

const getInstalledRequirement = `-- name: GetInstalledRequirement :one
SELECT required_digest FROM installed_package_requirements
WHERE org_id = $1 AND package_name = $2 AND required_name = $3
`

type GetInstalledRequirementParams struct {
	OrgID        string
	PackageName  string
	RequiredName string
}

func (q *Queries) GetInstalledRequirement(ctx context.Context, arg GetInstalledRequirementParams) (string, error) {
	row := q.db.QueryRow(ctx, getInstalledRequirement, arg.OrgID, arg.PackageName, arg.RequiredName)
	var required_digest string
	err := row.Scan(&required_digest)
	return required_digest, err
}

const insertInstalledPackage = `-- name: InsertInstalledPackage :exec
INSERT INTO installed_packages (org_id, name, reference, digest, descriptor, layer, update_policy)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertInstalledPackageParams struct {
	OrgID        string
	Name         string
	Reference    string
	Digest       string
	Descriptor   []byte
	Layer        []byte
	UpdatePolicy string
}

func (q *Queries) InsertInstalledPackage(ctx context.Context, arg InsertInstalledPackageParams) error {
	_, err := q.db.Exec(ctx, insertInstalledPackage,
		arg.OrgID,
		arg.Name,
		arg.Reference,
		arg.Digest,
		arg.Descriptor,
		arg.Layer,
		arg.UpdatePolicy,
	)
	return err
}

const insertInstalledRequirement = `-- name: InsertInstalledRequirement :exec
INSERT INTO installed_package_requirements (org_id, package_name, required_name, required_digest)
VALUES ($1, $2, $3, $4)
`

type InsertInstalledRequirementParams struct {
	OrgID          string
	PackageName    string
	RequiredName   string
	RequiredDigest string
}

func (q *Queries) InsertInstalledRequirement(ctx context.Context, arg InsertInstalledRequirementParams) error {
	_, err := q.db.Exec(ctx, insertInstalledRequirement,
		arg.OrgID,
		arg.PackageName,
		arg.RequiredName,
		arg.RequiredDigest,
	)
	return err
}

const listAutoUpdateInstalledPackages = `-- name: ListAutoUpdateInstalledPackages :many
SELECT org_id, name FROM installed_packages WHERE update_policy = 'auto' ORDER BY org_id, name
`

type ListAutoUpdateInstalledPackagesRow struct {
	OrgID string
	Name  string
}

func (q *Queries) ListAutoUpdateInstalledPackages(ctx context.Context) ([]ListAutoUpdateInstalledPackagesRow, error) {
	rows, err := q.db.Query(ctx, listAutoUpdateInstalledPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAutoUpdateInstalledPackagesRow
	for rows.Next() {
		var i ListAutoUpdateInstalledPackagesRow
		if err := rows.Scan(&i.OrgID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstalledPackages = `-- name: ListInstalledPackages :many
SELECT org_id, name, reference, digest, descriptor, layer, update_policy, accepted_authority,
    pending_reference, pending_digest, pending_authority, previous_reference, previous_digest, previous_accepted_authority
FROM installed_packages WHERE org_id = $1 ORDER BY name
`

type ListInstalledPackagesRow struct {
	OrgID                     string
	Name                      string
	Reference                 string
	Digest                    string
	Descriptor                []byte
	Layer                     []byte
	UpdatePolicy              string
	AcceptedAuthority         []byte
	PendingReference          pgtype.Text
	PendingDigest             pgtype.Text
	PendingAuthority          []byte
	PreviousReference         pgtype.Text
	PreviousDigest            pgtype.Text
	PreviousAcceptedAuthority []byte
}

func (q *Queries) ListInstalledPackages(ctx context.Context, orgID string) ([]ListInstalledPackagesRow, error) {
	rows, err := q.db.Query(ctx, listInstalledPackages, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstalledPackagesRow
	for rows.Next() {
		var i ListInstalledPackagesRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Name,
			&i.Reference,
			&i.Digest,
			&i.Descriptor,
			&i.Layer,
			&i.UpdatePolicy,
			&i.AcceptedAuthority,
			&i.PendingReference,
			&i.PendingDigest,
			&i.PendingAuthority,
			&i.PreviousReference,
			&i.PreviousDigest,
			&i.PreviousAcceptedAuthority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInstalledPackages = `-- name: LockInstalledPackages :exec
SELECT pg_advisory_xact_lock(hashtextextended('installed-packages:' || $1::text, 0))
`

func (q *Queries) LockInstalledPackages(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockInstalledPackages, dollar_1)
	return err
}

const replaceInstalledPackage = `-- name: ReplaceInstalledPackage :execrows
UPDATE installed_packages SET
    previous_reference = reference, previous_digest = digest,
    previous_accepted_authority = accepted_authority,
    reference = $3, digest = $4, descriptor = $5, layer = $6, accepted_authority = $7,
    pending_reference = NULL, pending_digest = NULL, pending_authority = NULL
WHERE org_id = $1 AND name = $2
`

type ReplaceInstalledPackageParams struct {
	OrgID             string
	Name              string
	Reference         string
	Digest            string
	Descriptor        []byte
	Layer             []byte
	AcceptedAuthority []byte
}

// The right-hand sides read the row as it was, so the replaced pin becomes
// the previous one in the same statement.
func (q *Queries) ReplaceInstalledPackage(ctx context.Context, arg ReplaceInstalledPackageParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceInstalledPackage,
		arg.OrgID,
		arg.Name,
		arg.Reference,
		arg.Digest,
		arg.Descriptor,
		arg.Layer,
		arg.AcceptedAuthority,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstalledPackagePending = `-- name: SetInstalledPackagePending :execrows
UPDATE installed_packages SET pending_reference = $3, pending_digest = $4, pending_authority = $5
WHERE org_id = $1 AND name = $2
`

type SetInstalledPackagePendingParams struct {
	OrgID            string
	Name             string
	PendingReference pgtype.Text
	PendingDigest    pgtype.Text
	PendingAuthority []byte
}

func (q *Queries) SetInstalledPackagePending(ctx context.Context, arg SetInstalledPackagePendingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInstalledPackagePending,
		arg.OrgID,
		arg.Name,
		arg.PendingReference,
		arg.PendingDigest,
		arg.PendingAuthority,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstalledPackageUpdatePolicy = `-- name: SetInstalledPackageUpdatePolicy :execrows
UPDATE installed_packages SET update_policy = $3 WHERE org_id = $1 AND name = $2
`

type SetInstalledPackageUpdatePolicyParams struct {
	OrgID        string
	Name         string
	UpdatePolicy string
}

func (q *Queries) SetInstalledPackageUpdatePolicy(ctx context.Context, arg SetInstalledPackageUpdatePolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInstalledPackageUpdatePolicy, arg.OrgID, arg.Name, arg.UpdatePolicy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
