// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installed_packages.sql

package postgresdb

import (
	"context"
)

const deleteInstalledPackage = `-- name: DeleteInstalledPackage :execrows
DELETE FROM installed_packages WHERE org_id = $1 AND name = $2
`

type DeleteInstalledPackageParams struct {
	OrgID string
	Name  string
}

func (q *Queries) DeleteInstalledPackage(ctx context.Context, arg DeleteInstalledPackageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstalledPackage, arg.OrgID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInstalledPackage = `-- name: GetInstalledPackage :one
SELECT org_id, name, reference, digest, descriptor, layer, update_policy
FROM installed_packages WHERE org_id = $1 AND name = $2
`

type GetInstalledPackageParams struct {
	OrgID string
	Name  string
}

type GetInstalledPackageRow struct {
	OrgID        string
	Name         string
	Reference    string
	Digest       string
	Descriptor   []byte
	Layer        []byte
	UpdatePolicy string
}

func (q *Queries) GetInstalledPackage(ctx context.Context, arg GetInstalledPackageParams) (GetInstalledPackageRow, error) {
	row := q.db.QueryRow(ctx, getInstalledPackage, arg.OrgID, arg.Name)
	var i GetInstalledPackageRow
	err := row.Scan(
		&i.OrgID,
		&i.Name,
		&i.Reference,
		&i.Digest,
		&i.Descriptor,
		&i.Layer,
		&i.UpdatePolicy,
	)
	return i, err
}

const getInstalledRequirement = `-- name: GetInstalledRequirement :one
SELECT required_digest FROM installed_package_requirements
WHERE org_id = $1 AND package_name = $2 AND required_name = $3
`

type GetInstalledRequirementParams struct {
	OrgID        string
	PackageName  string
	RequiredName string
}

func (q *Queries) GetInstalledRequirement(ctx context.Context, arg GetInstalledRequirementParams) (string, error) {
	row := q.db.QueryRow(ctx, getInstalledRequirement, arg.OrgID, arg.PackageName, arg.RequiredName)
	var required_digest string
	err := row.Scan(&required_digest)
	return required_digest, err
}

const insertInstalledPackage = `-- name: InsertInstalledPackage :exec
INSERT INTO installed_packages (org_id, name, reference, digest, descriptor, layer, update_policy)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertInstalledPackageParams struct {
	OrgID        string
	Name         string
	Reference    string
	Digest       string
	Descriptor   []byte
	Layer        []byte
	UpdatePolicy string
}

func (q *Queries) InsertInstalledPackage(ctx context.Context, arg InsertInstalledPackageParams) error {
	_, err := q.db.Exec(ctx, insertInstalledPackage,
		arg.OrgID,
		arg.Name,
		arg.Reference,
		arg.Digest,
		arg.Descriptor,
		arg.Layer,
		arg.UpdatePolicy,
	)
	return err
}

const insertInstalledRequirement = `-- name: InsertInstalledRequirement :exec
INSERT INTO installed_package_requirements (org_id, package_name, required_name, required_digest)
VALUES ($1, $2, $3, $4)
`

type InsertInstalledRequirementParams struct {
	OrgID          string
	PackageName    string
	RequiredName   string
	RequiredDigest string
}

func (q *Queries) InsertInstalledRequirement(ctx context.Context, arg InsertInstalledRequirementParams) error {
	_, err := q.db.Exec(ctx, insertInstalledRequirement,
		arg.OrgID,
		arg.PackageName,
		arg.RequiredName,
		arg.RequiredDigest,
	)
	return err
}

const listInstalledPackages = `-- name: ListInstalledPackages :many
SELECT org_id, name, reference, digest, descriptor, layer, update_policy
FROM installed_packages WHERE org_id = $1 ORDER BY name
`

type ListInstalledPackagesRow struct {
	OrgID        string
	Name         string
	Reference    string
	Digest       string
	Descriptor   []byte
	Layer        []byte
	UpdatePolicy string
}

func (q *Queries) ListInstalledPackages(ctx context.Context, orgID string) ([]ListInstalledPackagesRow, error) {
	rows, err := q.db.Query(ctx, listInstalledPackages, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstalledPackagesRow
	for rows.Next() {
		var i ListInstalledPackagesRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Name,
			&i.Reference,
			&i.Digest,
			&i.Descriptor,
			&i.Layer,
			&i.UpdatePolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInstalledPackages = `-- name: LockInstalledPackages :exec
SELECT pg_advisory_xact_lock(hashtextextended('installed-packages:' || $1::text, 0))
`

func (q *Queries) LockInstalledPackages(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockInstalledPackages, dollar_1)
	return err
}
