// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApplyStatus struct {
	Process        string
	Kind           string
	AppliedVersion int64
	Error          string
	ReportedAt     time.Time
}

type Binding struct {
	ID          string
	Name        string
	Source      string
	Mapping     string
	Workflow    string
	Owner       string
	Repo        string
	Version     int64
	Status      string
	Secret      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Filter      string
	Inputs      string
	RepoParam   string
	OrgID       string
	WorkspaceID string
}

type BindingDispatch struct {
	Binding        string
	BindingVersion int64
	Capture        string
	TaskID         int64
	DispatchedAt   time.Time
}

type Capture struct {
	ID            string
	Source        string
	RemoteAddr    string
	ContentType   string
	Headers       string
	Body          string
	Authenticated bool
	ReceivedAt    time.Time
	Unsigned      bool
	EventType     string
	OrgID         string
	WorkspaceID   string
}

type ChannelStatus struct {
	ID              string
	Name            string
	State           string
	Detail          string
	Configured      bool
	ReloadSupported bool
	ObservedAt      time.Time
}

type ConfigSnapshot struct {
	ID          int64
	Schema      string
	Document    string
	PublishedAt time.Time
}

type Event struct {
	ID          int64
	At          time.Time
	Kind        string
	TaskID      int64
	Repo        string
	Issue       int64
	Workflow    string
	Stage       string
	Attempt     int64
	ActorID     string
	ActorKind   string
	PrincipalID string
	Detail      string
	Data        string
	OrgID       string
	WorkspaceID string
}

type EventType struct {
	ID          string
	Source      string
	Name        string
	Rule        string
	Schema      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OrgID       string
	WorkspaceID string
}

type Identity struct {
	ID          string
	Kind        string
	DisplayName string
	Lifecycle   string
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type IdentityAlias struct {
	Alias      string
	IdentityID string
}

type IdentityEvent struct {
	ID            int64
	IdentityID    string
	EventType     string
	FromLifecycle string
	ToLifecycle   string
	DisplayName   string
	ActorID       string
	Source        string
	RequestID     string
	At            time.Time
}

type IdentitySubject struct {
	Issuer     string
	Subject    string
	IdentityID string
	BoundAt    time.Time
}

type InstalledPackage struct {
	OrgID        string
	Name         string
	Reference    string
	Digest       string
	Descriptor   []byte
	Layer        []byte
	UpdatePolicy string
	InstalledAt  time.Time
}

type InstalledPackageRequirement struct {
	OrgID          string
	PackageName    string
	RequiredName   string
	RequiredDigest string
}

type Mapping struct {
	ID          string
	Name        string
	SourceHint  string
	Fields      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	EventType   string
	OrgID       string
	WorkspaceID string
}

type MappingMatch struct {
	Mapping   string
	Capture   string
	MatchedAt time.Time
}

type Membership struct {
	IdentityID  string
	OrgID       string
	WorkspaceID pgtype.Text
	Role        string
	CreatedAt   time.Time
}

type Message struct {
	ID        int64
	MessageID string
	SessionID string
	SourceID  string
	Sender    string
	SenderID  string
	Role      string
	Text      string
	Ts        int64
	Search    interface{}
}

type Org struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrgAgent struct {
	IdentityID string
	OrgID      string
	CreatedAt  time.Time
}

type OrgUpgrade struct {
	Phase       string
	CompletedAt time.Time
}

type PlaybookDispatch struct {
	PlaybookID      string
	PlaybookVersion string
	EventID         string
	ActionID        string
	DispatchedAt    time.Time
}

type Resource struct {
	Kind      string
	Value     []byte
	Version   int64
	UpdatedAt time.Time
	OrgID     string
}

type ResourceHistory struct {
	ID              int64
	Kind            string
	Value           []byte
	Version         int64
	Actor           string
	Source          string
	RequestID       string
	ExpectedVersion int64
	CurrentVersion  int64
	At              time.Time
	OrgID           string
}

type Session struct {
	SessionID       string
	Platform        string
	BotUser         string
	ChannelID       string
	ThreadID        string
	Title           string
	ParentSessionID string
	BranchName      string
	CreatedAt       int64
	LastActiveAt    int64
}

type Source struct {
	Path        string
	Signing     string
	Secret      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OrgID       string
	WorkspaceID string
}

type SysAudit struct {
	ID            int64
	At            time.Time
	TableName     string
	RecordKey     string
	Field         string
	OldValue      []byte
	NewValue      []byte
	RecordVersion int64
	Actor         string
	Source        string
	RequestID     string
}

type Task struct {
	ID                        int64
	Owner                     string
	Repo                      string
	IssueNumber               int64
	Title                     string
	Body                      string
	Labels                    string
	Status                    string
	Workflow                  string
	Stage                     string
	Branch                    string
	Plan                      string
	Notes                     string
	PrNumber                  int64
	TokensUsed                int64
	Iterations                int64
	Attempt                   int64
	ParkReason                string
	WatchCommentID            int64
	ParkClass                 string
	RemediationRounds         int64
	RetryCount                int64
	Source                    string
	Identity                  string
	BindingID                 string
	BindingVersion            int64
	ReviewPayload             string
	WorkflowDefinitionVersion int64
	WorkflowDefinitionDigest  string
	WorkflowDefinitionYaml    string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	ReviewCursor              int64
	Inputs                    string
	OrgID                     string
	WorkspaceID               string
	CallParentTaskID          int64
	CallDepth                 int32
}

type ToolCall struct {
	ID          string
	TaskID      int64
	Attempt     int64
	Tool        string
	Args        string
	Result      string
	Error       string
	DurationMs  int64
	CalledAt    time.Time
	OrgID       string
	WorkspaceID string
}

type Transition struct {
	ID          int64
	TaskID      int64
	At          time.Time
	FromStatus  string
	ToStatus    string
	Detail      string
	OrgID       string
	WorkspaceID string
}

type Turn struct {
	TurnID             string
	SessionID          string
	SourceID           string
	Status             string
	Attempt            int64
	OwnerID            string
	InputMessageID     string
	AssistantMessageID string
	PartialText        string
	ResponseText       string
	ToolCalls          string
	Error              string
	CreatedAt          int64
	UpdatedAt          int64
}

type Workspace struct {
	ID          string
	OrgID       string
	Name        string
	Environment string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
