// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: steps.sql

package postgresdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishStepExecution = `-- name: FinishStepExecution :execrows
UPDATE step_executions
SET status = $1, detail = $2, tokens_used = $3, finished_at = now()
WHERE id = $4 AND status = $5
`

type FinishStepExecutionParams struct {
	Status     string
	Detail     string
	TokensUsed int64
	ID         int64
	Status_2   string
}

func (q *Queries) FinishStepExecution(ctx context.Context, arg FinishStepExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishStepExecution,
		arg.Status,
		arg.Detail,
		arg.TokensUsed,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertStepExecution = `-- name: InsertStepExecution :one
INSERT INTO step_executions (org_id, workspace_id, execution_id, attempt, parent_id, depth, kind, name, called_execution_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending')
RETURNING id
`

type InsertStepExecutionParams struct {
	OrgID             string
	WorkspaceID       string
	ExecutionID       int64
	Attempt           int64
	ParentID          pgtype.Int8
	Depth             int32
	Kind              string
	Name              string
	CalledExecutionID int64
}

func (q *Queries) InsertStepExecution(ctx context.Context, arg InsertStepExecutionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStepExecution,
		arg.OrgID,
		arg.WorkspaceID,
		arg.ExecutionID,
		arg.Attempt,
		arg.ParentID,
		arg.Depth,
		arg.Kind,
		arg.Name,
		arg.CalledExecutionID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockExecutionForStep = `-- name: LockExecutionForStep :one

SELECT id, status, org_id, workspace_id, owner, repo, issue_number, workflow, attempt
FROM tasks WHERE id = $1 FOR UPDATE
`

type LockExecutionForStepRow struct {
	ID          int64
	Status      string
	OrgID       string
	WorkspaceID string
	Owner       string
	Repo        string
	IssueNumber int64
	Workflow    string
	Attempt     int64
}

// Step-execution queries (docs/prds/execution-tree-state-machine.md). The
// store method owns the transaction that pairs each step transition with its
// event row; these are only the guarded row writes and reads.
// FOR UPDATE locks the execution's row, so the status check, the step insert
// and the event append are one serialized operation per execution -- the way
// guardTransition locks a task's row for its transition. The row also carries
// every field the transition's event needs (org, workspace, the task
// identity) and the attempt the step must belong to.
func (q *Queries) LockExecutionForStep(ctx context.Context, id int64) (LockExecutionForStepRow, error) {
	row := q.db.QueryRow(ctx, lockExecutionForStep, id)
	var i LockExecutionForStepRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.OrgID,
		&i.WorkspaceID,
		&i.Owner,
		&i.Repo,
		&i.IssueNumber,
		&i.Workflow,
		&i.Attempt,
	)
	return i, err
}

const lockStepExecution = `-- name: LockStepExecution :one
SELECT id, org_id, workspace_id, execution_id, attempt, parent_id, depth, kind, name, called_execution_id, status, detail, tokens_used, started_at, finished_at
FROM step_executions WHERE id = $1 FOR UPDATE
`

// FOR UPDATE, shared by a start's parent check and a finish's guarded write:
// the row is held for the caller's transaction, so the state a check reads is
// the state the guarded write sees.
func (q *Queries) LockStepExecution(ctx context.Context, id int64) (StepExecution, error) {
	row := q.db.QueryRow(ctx, lockStepExecution, id)
	var i StepExecution
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.WorkspaceID,
		&i.ExecutionID,
		&i.Attempt,
		&i.ParentID,
		&i.Depth,
		&i.Kind,
		&i.Name,
		&i.CalledExecutionID,
		&i.Status,
		&i.Detail,
		&i.TokensUsed,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const startStepExecution = `-- name: StartStepExecution :execrows
UPDATE step_executions SET status = 'running', started_at = now()
WHERE id = $1 AND status = 'pending'
`

// The pending -> running half of StartStep, guarded by the row's own status:
// the step transition table routes the pair, so a row that is not pending is
// stale rather than silently restarted.
func (q *Queries) StartStepExecution(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, startStepExecution, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
