// Package secretextract holds the Yaegi symbol table for internal/secret,
// generated by `go generate`. Kept separate from internal/secret itself
// so the generated file can import it without a self-import cycle.
//
// IMPORTANT: Running `go generate` overwrites the generated file with
// Yaegi's default wrapper which does NOT include nil-guards on function
// fields. The `TestGeneratedWrapperHasNilGuards` test catches this if
// regeneration strips the guards. Re-apply nil-guards manually after
// regeneration until Yaegi supports generating them natively.
package secretextract

import "reflect"

//go:generate go run github.com/traefik/yaegi/cmd/yaegi extract -name secretextract github.com/samcharles93/archie-core/internal/secret

var Symbols = map[string]map[string]reflect.Value{}
