// Code generated by 'yaegi extract github.com/samcharles93/archie-core/internal/domain/eda/module/log'. DO NOT EDIT.

package logextract

import (
	"go/constant"
	"go/token"
	"reflect"

	"github.com/samcharles93/archie-core/internal/domain/eda/module/log"
)

func init() {
	Symbols["github.com/samcharles93/archie-core/internal/domain/eda/module/log/log"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"SchemaVersion": reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),

		// type definitions
		"Args":   reflect.ValueOf((*log.Args)(nil)),
		"Result": reflect.ValueOf((*log.Result)(nil)),
	}
}
