// Package logextract holds the Yaegi symbol table for
// internal/domain/eda/module/log, generated by `go generate`. Kept separate
// from the log package itself so the generated file can import it without a
// self-import cycle.
//
// The generated file is used verbatim. A wrapper whose method fields are not
// all populated is refused in yaegiutil.Resolve, so it needs no hand-added
// nil-guards -- an earlier convention that every regeneration silently undid.
package logextract

import "reflect"

//go:generate go run github.com/traefik/yaegi/cmd/yaegi extract -name logextract github.com/samcharles93/archie-core/internal/domain/eda/module/log

var Symbols = map[string]map[string]reflect.Value{}
