// Package gateway defines the persistent-connection layer between archie
// and its users. Each gateway implementation (Telegram, web UI, Discord,
// etc.) owns its connection lifecycle and delegates message dispatch to a
// shared CommandRouter.
//
// The router distinguishes gateway-local commands  --  handled directly
// without the LLM (model changes, status queries, restart)  --  from
// general messages that need LLM processing.
package gateway

import (
	"context"
	"fmt"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"
)

// Message is an inbound message from a gateway connection.
type Message struct {
	// ChannelID identifies the conversation within the channel (e.g. a
	// Telegram chat ID). Replies are sent back to this ID.
	ChannelID string
	// ThreadID identifies the topic thread within the conversation, for
	// platforms that support threading (Telegram supergroup topics,
	// Slack threads, Discord forum posts). Empty for flat chats.
	ThreadID string
	// From identifies the sender (channel-specific: username, user ID).
	From string
	// Text is the raw message text, including any leading slash command.
	Text string
}

// A Gateway owns a persistent connection to a chat channel. Start blocks;
// the gateway should remain running until ctx is cancelled or Stop is
// called.
type Gateway interface {
	Name() string
	Start(ctx context.Context, router *Router) error
	Stop(ctx context.Context) error
}

// StatusReader is the read-only query surface gateway-local commands
// like /status need. The daemon supplies its store, which satisfies this
// structurally.
type StatusReader interface {
	StatusCounts(ctx context.Context) (map[string]int, error)
}

// SessionLister is the read surface /sessions and /resume need.
// The daemon supplies its session store, which satisfies this structurally.
type SessionLister interface {
	List(ctx context.Context) ([]SessionContext, error)
}

// AgentInfo carries one row for /agents.
type AgentInfo struct {
	ID       int64
	Title    string
	Status   string
	Identity string
}

// AgentReader is the read surface /agents needs. The daemon supplies
// its store, which satisfies this structurally.
type AgentReader interface {
	AgentList(ctx context.Context) ([]AgentInfo, error)
}

// LLMResponder routes a message to the LLM and returns the reply. When
// nil (not yet wired  --  see abg.13), non-command messages get a static
// "LLM not configured" response. Gateways call this for any message the
// router did not handle directly.
type LLMResponder func(ctx context.Context, msg Message) (string, error)

// LLMStreamResponder is the streaming counterpart of LLMResponder. It
// reports the reply as it is generated by calling onDelta with each new
// text fragment, and returns the complete reply when the turn finishes.
//
// It is optional: a gateway that cannot render partial output, or a
// deployment whose provider does not stream, simply leaves it nil and the
// Router falls back to the blocking LLMResponder. onDelta may be called
// from the generating goroutine and must not block for long  --  adapters
// should throttle their own network writes rather than stall the stream.
type LLMStreamResponder func(ctx context.Context, msg Message, onDelta func(string)) (string, error)

// ModelManager provides access to available models and allows switching the
// active LLM model. The daemon supplies an implementation backed by its
// runtime provider catalog. When nil on a Router, /model returns a
// "not configured" message.
type ModelManager interface {
	// Models returns all available model references in "provider/model" format.
	Models() []string
	// ActiveModel returns the currently active model reference.
	// Returns empty string when no model is active.
	ActiveModel() string
	// SetActiveModel switches the active model. Returns an error if the
	// reference is unknown.
	SetActiveModel(ctx context.Context, ref string) error
}

// ProviderModelManager is the optional provider-aware extension used by
// gateways that offer a provider selector before model selection.
type ProviderModelManager interface {
	ModelManager
	Providers() []string
	ActiveProvider() string
	ModelsForProvider(provider string) []string
	SetActiveProvider(ctx context.Context, provider string) error
}

// SpawnRequest is a chat-originated task creation request. Repo and
// Workflow are optional  --  empty means "the daemon's configured
// default for this identity".
type SpawnRequest struct {
	Title    string
	Repo     string // "owner/name"; empty = identity's default repo
	Workflow string // empty = daemon's default workflow routing
	Identity string // the identity spawning this task; propagated from Router.Identity
}

// TaskCreator creates a native (non-forge-backed) task from a chat
// command. The daemon supplies an implementation backed by the store.
// When nil on a Router, /spawn returns "not configured". CreateTask
// must return the task's real, durable database ID  --  never a
// synthetic or fabricated value.
type TaskCreator interface {
	CreateTask(ctx context.Context, req SpawnRequest) (taskID int64, err error)
}

// TaskController approves or cancels a chat-originated task. Both
// methods must enforce authorization (identity must own the task) and
// valid state transitions; see gateway.tasks.go's StoreTaskController
// for the reference implementation. When nil on a Router, /approve and
// /cancel return "not configured".
type TaskController interface {
	// Approve moves a waiting_human task back to queued. Returns an
	// error (surfaced to the user, not the LLM) if the task doesn't
	// exist, isn't owned by identity, or isn't in waiting_human.
	Approve(ctx context.Context, taskID int64, identity string) error
	// Cancel moves an active (non-terminal, non-running) task to a
	// rejected/cancelled terminal state. Returns an error if the task
	// doesn't exist, isn't owned by identity, or is already terminal
	// or actively running.
	Cancel(ctx context.Context, taskID int64, identity string) error
}

// Router dispatches inbound messages. Gateway-local commands (like
// /status) are handled directly. Everything else is routed to the LLM
// responder. Gateway implementations call Route on every inbound
// message.
type Router struct {
	Store      StatusReader
	Models     ModelManager   // nil = /model not configured
	Tasks      TaskCreator    // nil = /spawn not configured
	Controller TaskController // nil = /approve and /cancel not configured
	LLM        LLMResponder   // nil = LLM not wired yet
	// LLMStream is the optional streaming responder. When set, adapters
	// that can render partial output (see RouteStream) show the reply as
	// it generates; when nil, everything falls back to LLM.
	LLMStream LLMStreamResponder
	// Identity is the archie identity this router belongs to (empty in
	// single-identity deployments). Propagated into SpawnRequest and
	// used to scope /approve and /cancel authorization  --  a task
	// spawned under one identity cannot be controlled from another's
	// chat session.
	Identity string
	// Sessions supports /sessions and /resume. When nil those commands
	// return "not configured".
	Sessions SessionLister
	// Agents supports /agents. When nil the command returns
	// "not configured".
	Agents      AgentReader
	gatewayName string
}

// NewRouter returns a Router. llm is optional  --  when nil, non-command
// messages get a "not configured" response.
func NewRouter(store StatusReader, llm LLMResponder, gatewayName string) *Router {
	return &Router{Store: store, LLM: llm, gatewayName: gatewayName}
}

// Route dispatches msg and returns the reply. Gateway-local commands
// (like /status and /model) are handled directly; everything
// else goes to the LLM responder.
func (r *Router) Route(ctx context.Context, msg Message) (string, error) {
	text := strings.TrimSpace(msg.Text)
	cmd, arg := parseCmd(text, r.gatewayName)

	switch cmd {
	case "/status":
		return r.handleStatus(ctx)
	case "/model":
		return r.handleModel(ctx, arg)
	case "/spawn":
		// Title is everything after "/spawn"  --  keep the multi-word text.
		rest := restAfter(text, cmd, r.gatewayName)
		return r.handleSpawn(ctx, rest)
	case "/whoami":
		return r.handleWhoami()
	case "/profile":
		return r.handleProfile()
	case "/sessions":
		return r.handleSessions(ctx)
	case "/resume":
		return r.handleResume(ctx, restAfter(text, cmd, r.gatewayName))
	case "/agents":
		return r.handleAgents(ctx)
	case "/approve":
		// Reserved for dangerous-command approval (archie-core-alm.6).
		// Telegram hides it from its menu/help; other gateways keep it
		// wired until the new design is wired up.
		return r.handleApprove(ctx, restAfter(text, cmd, r.gatewayName))
	case "/cancel":
		return r.handleCancel(ctx, restAfter(text, cmd, r.gatewayName))
	default:
		if strings.HasPrefix(cmd, "/") {
			return fmt.Sprintf("Unknown command %s. Try /help.", cmd), nil
		}
		if r.LLM == nil {
			return "I'm running but LLM processing isn't wired yet. Try /status.", nil
		}
		return r.LLM(ctx, msg)
	}
}

// RouteStream is Route for adapters that can render a reply progressively.
// onDelta receives each new fragment of an LLM reply as it is generated;
// the complete reply is returned as usual.
//
// Only free-text messages stream. Gateway-local commands (/status, /model,
// …) answer from local state in a single step, so they return through the
// normal path with no delta callbacks. When no streaming responder is
// configured, RouteStream is exactly Route  --  callers get the whole reply
// at the end and simply never see a delta, so an adapter can always call
// RouteStream without checking first.
func (r *Router) RouteStream(ctx context.Context, msg Message, onDelta func(string)) (string, error) {
	if r.LLMStream == nil || onDelta == nil {
		return r.Route(ctx, msg)
	}
	cmd, _ := parseCmd(strings.TrimSpace(msg.Text), r.gatewayName)
	if isLocalCommand(cmd) || strings.HasPrefix(cmd, "/") {
		return r.Route(ctx, msg)
	}
	return r.LLMStream(ctx, msg, onDelta)
}

var localCommands = []string{"/status", "/model", "/spawn", "/whoami", "/profile", "/sessions", "/resume", "/agents", "/approve", "/cancel"}

// LocalCommands returns the command names Route answers from local state.
// Gateways use this to verify that their published command surfaces match
// the executable router surface.
func LocalCommands() []string {
	return slices.Clone(localCommands)
}

// isLocalCommand reports whether cmd is answered from local state by
// Route rather than handed to the LLM.
func isLocalCommand(cmd string) bool {
	return slices.Contains(localCommands, cmd)
}

// parseCmd extracts the command name from text, stripping an optional
// @gateway mention from the command token, and returns the command and
// its first argument.
func parseCmd(text, gatewayName string) (cmd, arg string) {
	fields := strings.Fields(text)
	if len(fields) == 0 {
		return "", ""
	}
	raw := fields[0]
	if gatewayName != "" {
		suffix := "@" + gatewayName
		raw = strings.TrimSuffix(raw, suffix)
	}
	if len(fields) > 1 {
		return raw, fields[1]
	}
	return raw, ""
}

func (r *Router) handleModel(ctx context.Context, arg string) (string, error) {
	if r.Models == nil {
		return "Model switching is not configured.", nil
	}
	if arg == "" {
		models := r.Models.Models()
		if manager, ok := r.Models.(ProviderModelManager); ok {
			models = manager.ModelsForProvider(manager.ActiveProvider())
		}
		if len(models) == 0 {
			return "No models configured.\nUsage: /model <provider/model>", nil
		}
		var b strings.Builder
		b.WriteString("Usage: /model <provider/model>\nAvailable models:\n")
		active := r.Models.ActiveModel()
		for _, m := range models {
			if m == active {
				fmt.Fprintf(&b, "  %s (active)\n", m)
			} else {
				fmt.Fprintf(&b, "  %s\n", m)
			}
		}
		return b.String(), nil
	}
	if err := r.Models.SetActiveModel(ctx, arg); err != nil {
		return fmt.Sprintf("Cannot switch: %v", err), nil
	}
	return fmt.Sprintf("Active model set to %s.", arg), nil
}

// restAfter returns the text after the command token, stripping the
// optional @gateway mention. E.g. for "/spawn Fix the bug", returns
// "Fix the bug".
func restAfter(text, cmd, gatewayName string) string {
	s := text
	if gatewayName != "" {
		s = strings.TrimPrefix(s, cmd+"@"+gatewayName)
	}
	s = strings.TrimPrefix(s, cmd)
	return strings.TrimSpace(s)
}

// handleSpawn parses optional leading identity, repo, and workflow tokens
// off rest, treating whatever remains as the task title.
func (r *Router) handleSpawn(ctx context.Context, rest string) (string, error) {
	if r.Tasks == nil {
		return "Task creation is not configured.", nil
	}
	req := SpawnRequest{Identity: r.Identity}
	fields := strings.Fields(rest)
	i := 0
	for i < len(fields) {
		if after, ok := strings.CutPrefix(fields[i], "identity="); ok {
			req.Identity = after
			i++
			continue
		}
		if after, ok := strings.CutPrefix(fields[i], "repo="); ok {
			req.Repo = after
			i++
			continue
		}
		if after, ok := strings.CutPrefix(fields[i], "workflow="); ok {
			req.Workflow = after
			i++
			continue
		}
		break // remaining fields are all title
	}
	req.Title = strings.TrimSpace(strings.Join(fields[i:], " "))
	if req.Title == "" {
		return "Usage: /spawn [identity=name] [repo=owner/name] [workflow=name] <title>", nil
	}
	id, err := r.Tasks.CreateTask(ctx, req)
	if err != nil {
		return fmt.Sprintf("Failed to create task: %v", err), nil
	}
	return fmt.Sprintf("Created task %d: %s", id, req.Title), nil
}

// parseTaskID parses a chat command argument as a task database ID.
func parseTaskID(arg string) (int64, error) {
	if arg == "" {
		return 0, fmt.Errorf("missing task ID")
	}
	id, err := strconv.ParseInt(arg, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("%q is not a valid task ID", arg)
	}
	return id, nil
}

func (r *Router) handleApprove(ctx context.Context, rest string) (string, error) {
	if r.Controller == nil {
		return "Task control is not configured.", nil
	}
	identity, arg := parseTaskControl(rest, r.Identity)
	id, err := parseTaskID(arg)
	if err != nil {
		return "Usage: /approve [identity=name] <task-id>", nil //nolint:nilerr // chat commands report problems as text to the human, never as Go errors, which would surface as a gateway fault
	}
	if err := r.Controller.Approve(ctx, id, identity); err != nil {
		return fmt.Sprintf("Cannot approve task %d: %v", id, err), nil
	}
	return fmt.Sprintf("Task %d approved and requeued.", id), nil
}

func (r *Router) handleCancel(ctx context.Context, rest string) (string, error) {
	if r.Controller == nil {
		return "Task control is not configured.", nil
	}
	identity, arg := parseTaskControl(rest, r.Identity)
	id, err := parseTaskID(arg)
	if err != nil {
		return "Usage: /cancel [identity=name] <task-id>", nil //nolint:nilerr // chat commands report problems as text to the human, never as Go errors, which would surface as a gateway fault
	}
	if err := r.Controller.Cancel(ctx, id, identity); err != nil {
		return fmt.Sprintf("Cannot cancel task %d: %v", id, err), nil
	}
	return fmt.Sprintf("Task %d cancelled.", id), nil
}

func parseTaskControl(rest, defaultIdentity string) (identity, taskID string) {
	fields := strings.Fields(rest)
	identity = defaultIdentity
	if len(fields) > 0 && strings.HasPrefix(fields[0], "identity=") {
		identity = strings.TrimPrefix(fields[0], "identity=")
		fields = fields[1:]
	}
	if len(fields) != 1 {
		return identity, ""
	}
	return identity, fields[0]
}

func (r *Router) handleStatus(ctx context.Context) (string, error) {
	if r.Store == nil {
		return "store not configured", nil
	}
	counts, err := r.Store.StatusCounts(ctx)
	if err != nil {
		return "", fmt.Errorf("status: %w", err)
	}
	if len(counts) == 0 && r.Models == nil {
		return "No tasks yet.", nil
	}
	statuses := make([]string, 0, len(counts))
	for s := range counts {
		statuses = append(statuses, s)
	}
	sort.Strings(statuses)

	var b strings.Builder
	if len(statuses) == 0 {
		b.WriteString("No tasks yet.\n")
	} else {
		b.WriteString("Task status:\n")
		for _, s := range statuses {
			fmt.Fprintf(&b, "  %s: %d\n", s, counts[s])
		}
	}
	if r.Models != nil {
		if manager, ok := r.Models.(ProviderModelManager); ok {
			fmt.Fprintf(&b, "\nProvider: %s\n", manager.ActiveProvider())
		}
		fmt.Fprintf(&b, "Model: %s\n", r.Models.ActiveModel())
	}
	return strings.TrimSpace(b.String()), nil
}

// ── /whoami ───────────────────────────────────────────────────────

func (r *Router) handleWhoami() (string, error) {
	var b strings.Builder
	b.WriteString("You are talking to Archie")
	if r.Identity != "" {
		fmt.Fprintf(&b, " (%s)", r.Identity)
	}
	b.WriteString(".\n")

	if r.Models != nil {
		if manager, ok := r.Models.(ProviderModelManager); ok {
			fmt.Fprintf(&b, "Provider: %s\n", manager.ActiveProvider())
		}
		fmt.Fprintf(&b, "Model: %s\n", r.Models.ActiveModel())
	}
	return strings.TrimSpace(b.String()), nil
}

// ── /profile ──────────────────────────────────────────────────────

func (r *Router) handleProfile() (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "*Archie profile*\n")
	if r.Identity != "" {
		fmt.Fprintf(&b, "Identity: `%s`\n", r.Identity)
	} else {
		b.WriteString("Identity: _(not configured)_\n")
	}

	if r.Models == nil {
		return strings.TrimSpace(b.String()), nil
	}

	if manager, ok := r.Models.(ProviderModelManager); ok {
		fmt.Fprintf(&b, "Provider: `%s`\n", manager.ActiveProvider())
	}
	fmt.Fprintf(&b, "Model: `%s`\n", r.Models.ActiveModel())

	models := r.Models.Models()
	if manager, ok := r.Models.(ProviderModelManager); ok {
		models = manager.ModelsForProvider(manager.ActiveProvider())
	}
	if len(models) == 0 {
		return strings.TrimSpace(b.String()), nil
	}

	b.WriteString("Available models:\n")
	active := r.Models.ActiveModel()
	for _, m := range models {
		if m == active {
			fmt.Fprintf(&b, "  `%s` _(active)_\n", m)
		} else {
			fmt.Fprintf(&b, "  `%s`\n", m)
		}
	}
	return strings.TrimSpace(b.String()), nil
}

// ── /sessions ─────────────────────────────────────────────────────

func (r *Router) handleSessions(ctx context.Context) (string, error) {
	if r.Sessions == nil {
		return "Session listing is not configured.", nil
	}
	sessions, err := r.Sessions.List(ctx)
	if err != nil {
		return "", fmt.Errorf("sessions: %w", err)
	}
	if len(sessions) == 0 {
		return "No sessions yet.", nil
	}
	var b strings.Builder
	b.WriteString("*Sessions*\n")
	for _, sc := range sessions {
		ago := time.Since(sc.LastActiveAt).Truncate(time.Second)
		fmt.Fprintf(&b, "`%s`\n  last active %s ago", sc.SessionID, ago)
		if sc.Source.ThreadID != "" {
			fmt.Fprintf(&b, " (thread %s)", sc.Source.ThreadID)
		}
		b.WriteByte('\n')
	}
	return strings.TrimSpace(b.String()), nil
}

// ── /resume ───────────────────────────────────────────────────────

func (r *Router) handleResume(ctx context.Context, name string) (string, error) {
	if r.Sessions == nil {
		return "Session resume is not configured.", nil
	}
	if name == "" {
		return "Usage: /resume <session-id or name prefix>", nil
	}
	sessions, err := r.Sessions.List(ctx)
	if err != nil {
		return "", fmt.Errorf("resume: %w", err)
	}
	// Match by exact session ID or prefix.
	var matches []SessionContext
	for _, sc := range sessions {
		if sc.SessionID == name || strings.HasPrefix(sc.SessionID, name) {
			matches = append(matches, sc)
		}
	}
	if len(matches) == 0 {
		return fmt.Sprintf("No session matching %q found.", name), nil
	}
	if len(matches) > 1 {
		var b strings.Builder
		b.WriteString("Multiple sessions match:\n")
		for _, sc := range matches {
			fmt.Fprintf(&b, "  `%s`\n", sc.SessionID)
		}
		b.WriteString("Use the full session ID to resume a specific one.")
		return b.String(), nil
	}
	sc := matches[0]
	return fmt.Sprintf("Resumed session `%s` (last active %s ago). Send a message to continue.",
		sc.SessionID, time.Since(sc.LastActiveAt).Truncate(time.Second)), nil
}

// ── /agents ───────────────────────────────────────────────────────

func (r *Router) handleAgents(ctx context.Context) (string, error) {
	if r.Agents == nil {
		return "Agent listing is not configured.", nil
	}
	agents, err := r.Agents.AgentList(ctx)
	if err != nil {
		return "", fmt.Errorf("agents: %w", err)
	}
	if len(agents) == 0 {
		return "No active agents or running tasks.", nil
	}
	var b strings.Builder
	b.WriteString("*Active agents*\n")
	for _, a := range agents {
		fmt.Fprintf(&b, "`%d` %s", a.ID, a.Title)
		if a.Identity != "" {
			fmt.Fprintf(&b, " _(%s)_", a.Identity)
		}
		fmt.Fprintf(&b, "  \nStatus: %s\n", a.Status)
	}
	return strings.TrimSpace(b.String()), nil
}
