// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: harness/v1/harness.proto

package harnessv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenRequest is one client frame. The first frame must be target; a frame
// with no field set is a keepalive the server ignores.
type OpenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*OpenRequest_Target
	//	*OpenRequest_Stdin
	Frame isOpenRequest_Frame `protobuf_oneof:"frame"`
	// size is the terminal size the client wants, in character cells. The
	// dashboard sends it with the target frame so the PTY is created at the
	// right size; the daemon falls back to its own default when it is absent.
	Size          *ConsoleSize `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_harness_v1_harness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_v1_harness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_harness_v1_harness_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetFrame() isOpenRequest_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *OpenRequest) GetTarget() *OpenTarget {
	if x != nil {
		if x, ok := x.Frame.(*OpenRequest_Target); ok {
			return x.Target
		}
	}
	return nil
}

func (x *OpenRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Frame.(*OpenRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *OpenRequest) GetSize() *ConsoleSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type isOpenRequest_Frame interface {
	isOpenRequest_Frame()
}

type OpenRequest_Target struct {
	// target names the session and must be the first frame.
	Target *OpenTarget `protobuf:"bytes,1,opt,name=target,proto3,oneof"`
}

type OpenRequest_Stdin struct {
	// stdin is terminal input bytes.
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

func (*OpenRequest_Target) isOpenRequest_Frame() {}

func (*OpenRequest_Stdin) isOpenRequest_Frame() {}

// OpenResponse is one server frame.
type OpenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*OpenResponse_Stdout
	//	*OpenResponse_ExitCode
	//	*OpenResponse_Error
	Frame         isOpenResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_harness_v1_harness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_v1_harness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_harness_v1_harness_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResponse) GetFrame() isOpenResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *OpenResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Frame.(*OpenResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *OpenResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Frame.(*OpenResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *OpenResponse) GetError() string {
	if x != nil {
		if x, ok := x.Frame.(*OpenResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isOpenResponse_Frame interface {
	isOpenResponse_Frame()
}

type OpenResponse_Stdout struct {
	// stdout is terminal output bytes.
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type OpenResponse_ExitCode struct {
	// exit_code ends the session: the command's exit status.
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

type OpenResponse_Error struct {
	// error ends the session when it could not be opened or was aborted.
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*OpenResponse_Stdout) isOpenResponse_Frame() {}

func (*OpenResponse_ExitCode) isOpenResponse_Frame() {}

func (*OpenResponse_Error) isOpenResponse_Frame() {}

// OpenTarget addresses one session. A setup session is addressed by Kit
// profile and is ephemeral; a run session is addressed by task and attempt and
// is bounded by the task.
type OpenTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Org   string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*OpenTarget_Setup
	//	*OpenTarget_Run
	Target        isOpenTarget_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTarget) Reset() {
	*x = OpenTarget{}
	mi := &file_harness_v1_harness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTarget) ProtoMessage() {}

func (x *OpenTarget) ProtoReflect() protoreflect.Message {
	mi := &file_harness_v1_harness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTarget.ProtoReflect.Descriptor instead.
func (*OpenTarget) Descriptor() ([]byte, []int) {
	return file_harness_v1_harness_proto_rawDescGZIP(), []int{2}
}

func (x *OpenTarget) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *OpenTarget) GetTarget() isOpenTarget_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *OpenTarget) GetSetup() *SetupTarget {
	if x != nil {
		if x, ok := x.Target.(*OpenTarget_Setup); ok {
			return x.Setup
		}
	}
	return nil
}

func (x *OpenTarget) GetRun() *RunTarget {
	if x != nil {
		if x, ok := x.Target.(*OpenTarget_Run); ok {
			return x.Run
		}
	}
	return nil
}

type isOpenTarget_Target interface {
	isOpenTarget_Target()
}

type OpenTarget_Setup struct {
	Setup *SetupTarget `protobuf:"bytes,2,opt,name=setup,proto3,oneof"`
}

type OpenTarget_Run struct {
	Run *RunTarget `protobuf:"bytes,3,opt,name=run,proto3,oneof"`
}

func (*OpenTarget_Setup) isOpenTarget_Target() {}

func (*OpenTarget_Run) isOpenTarget_Target() {}

// SetupTarget runs the CLI's own login in an ephemeral container built from
// the named agent profile's Kit.
type SetupTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupTarget) Reset() {
	*x = SetupTarget{}
	mi := &file_harness_v1_harness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupTarget) ProtoMessage() {}

func (x *SetupTarget) ProtoReflect() protoreflect.Message {
	mi := &file_harness_v1_harness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupTarget.ProtoReflect.Descriptor instead.
func (*SetupTarget) Descriptor() ([]byte, []int) {
	return file_harness_v1_harness_proto_rawDescGZIP(), []int{3}
}

func (x *SetupTarget) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

// RunTarget is a running task's container. It is reserved for the run-scoped
// live view; this version answers Unimplemented for it.
type RunTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Attempt       int64                  `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTarget) Reset() {
	*x = RunTarget{}
	mi := &file_harness_v1_harness_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTarget) ProtoMessage() {}

func (x *RunTarget) ProtoReflect() protoreflect.Message {
	mi := &file_harness_v1_harness_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTarget.ProtoReflect.Descriptor instead.
func (*RunTarget) Descriptor() ([]byte, []int) {
	return file_harness_v1_harness_proto_rawDescGZIP(), []int{4}
}

func (x *RunTarget) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RunTarget) GetAttempt() int64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

// ConsoleSize is a terminal size in character cells.
type ConsoleSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleSize) Reset() {
	*x = ConsoleSize{}
	mi := &file_harness_v1_harness_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleSize) ProtoMessage() {}

func (x *ConsoleSize) ProtoReflect() protoreflect.Message {
	mi := &file_harness_v1_harness_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleSize.ProtoReflect.Descriptor instead.
func (*ConsoleSize) Descriptor() ([]byte, []int) {
	return file_harness_v1_harness_proto_rawDescGZIP(), []int{5}
}

func (x *ConsoleSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ConsoleSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

var File_harness_v1_harness_proto protoreflect.FileDescriptor

const file_harness_v1_harness_proto_rawDesc = "" +
	"\n" +
	"\x18harness/v1/harness.proto\x12\n" +
	"harness.v1\"\x8d\x01\n" +
	"\vOpenRequest\x120\n" +
	"\x06target\x18\x01 \x01(\v2\x16.harness.v1.OpenTargetH\x00R\x06target\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12+\n" +
	"\x04size\x18\x03 \x01(\v2\x17.harness.v1.ConsoleSizeR\x04sizeB\a\n" +
	"\x05frame\"h\n" +
	"\fOpenResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x1d\n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCode\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\a\n" +
	"\x05frame\"\x84\x01\n" +
	"\n" +
	"OpenTarget\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12/\n" +
	"\x05setup\x18\x02 \x01(\v2\x17.harness.v1.SetupTargetH\x00R\x05setup\x12)\n" +
	"\x03run\x18\x03 \x01(\v2\x15.harness.v1.RunTargetH\x00R\x03runB\b\n" +
	"\x06target\"'\n" +
	"\vSetupTarget\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\">\n" +
	"\tRunTarget\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\x03R\aattempt\"5\n" +
	"\vConsoleSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols2O\n" +
	"\x0eHarnessService\x12=\n" +
	"\x04Open\x12\x17.harness.v1.OpenRequest\x1a\x18.harness.v1.OpenResponse(\x010\x01B\xb4\x01\n" +
	"\x0ecom.harness.v1B\fHarnessProtoP\x01ZKgithub.com/samcharles93/archie-core/internal/contracts/harness/v1;harnessv1\xa2\x02\x03HXX\xaa\x02\n" +
	"Harness.V1\xca\x02\n" +
	"Harness\\V1\xe2\x02\x16Harness\\V1\\GPBMetadata\xea\x02\vHarness::V1b\x06proto3"

var (
	file_harness_v1_harness_proto_rawDescOnce sync.Once
	file_harness_v1_harness_proto_rawDescData []byte
)

func file_harness_v1_harness_proto_rawDescGZIP() []byte {
	file_harness_v1_harness_proto_rawDescOnce.Do(func() {
		file_harness_v1_harness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_harness_v1_harness_proto_rawDesc), len(file_harness_v1_harness_proto_rawDesc)))
	})
	return file_harness_v1_harness_proto_rawDescData
}

var file_harness_v1_harness_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_harness_v1_harness_proto_goTypes = []any{
	(*OpenRequest)(nil),  // 0: harness.v1.OpenRequest
	(*OpenResponse)(nil), // 1: harness.v1.OpenResponse
	(*OpenTarget)(nil),   // 2: harness.v1.OpenTarget
	(*SetupTarget)(nil),  // 3: harness.v1.SetupTarget
	(*RunTarget)(nil),    // 4: harness.v1.RunTarget
	(*ConsoleSize)(nil),  // 5: harness.v1.ConsoleSize
}
var file_harness_v1_harness_proto_depIdxs = []int32{
	2, // 0: harness.v1.OpenRequest.target:type_name -> harness.v1.OpenTarget
	5, // 1: harness.v1.OpenRequest.size:type_name -> harness.v1.ConsoleSize
	3, // 2: harness.v1.OpenTarget.setup:type_name -> harness.v1.SetupTarget
	4, // 3: harness.v1.OpenTarget.run:type_name -> harness.v1.RunTarget
	0, // 4: harness.v1.HarnessService.Open:input_type -> harness.v1.OpenRequest
	1, // 5: harness.v1.HarnessService.Open:output_type -> harness.v1.OpenResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_harness_v1_harness_proto_init() }
func file_harness_v1_harness_proto_init() {
	if File_harness_v1_harness_proto != nil {
		return
	}
	file_harness_v1_harness_proto_msgTypes[0].OneofWrappers = []any{
		(*OpenRequest_Target)(nil),
		(*OpenRequest_Stdin)(nil),
	}
	file_harness_v1_harness_proto_msgTypes[1].OneofWrappers = []any{
		(*OpenResponse_Stdout)(nil),
		(*OpenResponse_ExitCode)(nil),
		(*OpenResponse_Error)(nil),
	}
	file_harness_v1_harness_proto_msgTypes[2].OneofWrappers = []any{
		(*OpenTarget_Setup)(nil),
		(*OpenTarget_Run)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_harness_v1_harness_proto_rawDesc), len(file_harness_v1_harness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_harness_v1_harness_proto_goTypes,
		DependencyIndexes: file_harness_v1_harness_proto_depIdxs,
		MessageInfos:      file_harness_v1_harness_proto_msgTypes,
	}.Build()
	File_harness_v1_harness_proto = out.File
	file_harness_v1_harness_proto_goTypes = nil
	file_harness_v1_harness_proto_depIdxs = nil
}
